### ISSUE TITLE
Request: Allow images in posts (not comments) to scale to fit

### ISSUE THREAD

**Issue by jasonkhanlar** [ruqqus/ruqqus#123]
See:

https://www.ruqqus.com/post/115

https://www.reddit.com/r/test/comments/f5yn3d/test/

Request: Allow images embedded in original posts to be scaled to fit. Note: On Reddit, It does not seem possible to embed pictures in comments, only in the post.

**Comment by jasonkhanlar** [comment]
I just tried to embed another image into a new post, but the image HTML was converted into a link.

https://www.ruqqus.com/post/1ez is the post

This is the content I initially submitted for the post: (See https://web.archive.org/web/20200229040728/https://www.ruqqus.com/post/1ez)

```html
<img alt="Selfie" src="https://files.catbox.moe/bmg5wx.png" class="testing">

credit/source: https://www.deviantart.com/mioko-san/art/17-08-2013-394446656```

I also tried using Markdown (that previously worked too):
```markdown
<!-- <img alt="Selfie" src="https://files.catbox.moe/bmg5wx.png" class="testing"> -->
![Selfie?](https://files.catbox.moe/bmg5wx.png "Selfie")

credit/source: https://www.deviantart.com/mioko-san/art/17-08-2013-394446656```

but even that is also converted into a link, and no embedded image appears anymore at all.

8 days ago https://www.ruqqus.com/post/115 embedding images was possible.

I was hoping to be able to present a single image full width, like video embeds appear, since I see no reason why images should be discriminated against compared to video content.

**Comment by arkit3kt** [comment]
functionality already exists.
