### ISSUE TITLE
Add AJAX-style replying 

### ISSUE THREAD

**Issue by jasonkhanlar** [ruqqus/ruqqus#133]
Please implement AJAX-style replying such that when filling out the embedded comment reply form, after submitting, instead of reloading to an entirely new web page, stay on the same web page and inject the reply to appear into the web page DOM.

This will offer a lot faster user experience, and also reduce the bandwidth footprint required to send/receive data to clients for engaging with the site.

**Comment by captainmeta4** [comment]
coming in next minor update
