### ISSUE TITLE
Feature idea: Clans/squads/tribes/factions/teams/guilds/fraternities/parties/teams/whatever you wanna call it

### ISSUE THREAD

**Issue by jasonkhanlar** [ruqqus/ruqqus#134]
I was just thinking, for a few guilds that I created, I think they are generic enough that like the +Quarantine guild, I am tempted to invite practically everyone (that is a member as of now anyway), to be a guildmaster, especially to help distribute the effort for the simple primary task of:

- yanking posts that are appropriate into the guild to be yanked into the guild by whomever realizes first to yank into the guild

For example, the +RequestAGuild guild

but also to reduce all the effort in individually sending invitation to a bunch of users to become guildmasters for that guild too, and then another guild, and another, and another, etc., it would be really cool if there were a kind of system in which users can join a clan, squad, tribe, faction, team, whatever-you-wanna-call-it group/community of members, in which that group unit can be sent an invitation instead of individually each of the users.

-

A guild(1) of guildmasters of guilds(2)

Note: guild(1) is NOT EQUAL to guild(2), otherwise infinite recursion

**Comment by captainmeta4** [comment]
I don't even understand what you're askng
