### ISSUE TITLE
Feature Request: Allow users to mute/block other users, and mute/filter entire guilds from appearing in all, etc

### ISSUE THREAD

**Issue by jasonkhanlar** [ruqqus/ruqqus#141]
Like on Twitter, allow users to mute and block other users.

Add a way to let users hide any posts from muted/blocked users from appearing in feeds (Twitter-style), affecting only their accounts, nobody else's

Add a way to let users mute/block/filter guilds too, from appearing in feeds, especially the all feed (and the potential future (All - Home) feed

Also I see at <https://old.reddit.com/r/all/> on right side:
```
Displaying content from /r/all, except the following subreddits:
___________________________
» Exclude your communities
» See gilded comments and submissions
```

I see the URL for "Exclude your communities" is like:

<https://old.reddit.com/r/all-subreddit1-subreddit2-subreddit3-subreddit4-etc.....>

**Comment by jasonkhanlar** [comment]
Also linking https://github.com/ruqqus/ruqqus/issues/136 to consider that muted/filtered guilds should also be excluded from All - Home

**Comment by captainmeta4** [comment]
User blocking is coming
