### ISSUE TITLE
CSS Suggestions (Based on Dark mode only, Light mode untested)

### ISSUE THREAD

**Issue by jasonkhanlar** [ruqqus/ruqqus#142]
Note: All of these are suggested based on using Dark mode

1) Fix background of left side panel to be responsive
For example when at home page, pushing F12 to open developer tools to fill half the height of web browser, then scrolling to bottom of the website, the background for the left side panel is cut off

2) Home page - Hovering over username in a post, color is difficult to read: dark on dark
Suggestion: `a:hover { color: #766bd3; }`

3) Page navigation prev/next links color is dark on dark (on hover)
Suggestion: `.page-link:hover { color: #766bd3; }`

4) Home page sort dropdown color (hover, before clicking) -- make sure to not include #dropdownMenuButton:hover for other pages that have different styles for some reason
Suggestion: `.justify-content-between #dropdownMenuButton:hover { color: #8c8d94 !important; }`

5) Home page sort dropdown color (when clicked/expanded) -- make sure to not include #dropdownMenuButton:hover for other pages that have different styles for some reason
Suggestion: `.justify-content-between #dropdownMenuButton[aria-expanded=true] { color: #8c8d94 !important; }`

6) Guild browse page guild name color (on hover)
Suggestion: `div[id^=board-] .card-title:hover { color: #766bd3; }`

7) Guild content page post entry (hover) background color becomes white
Suggestion: `#guild .posts .card:hover { background-color: rgba(235,233,239, 0.1); }`
Also check hover colors of child elements inside the post entry

8) User page text color on variable background image
White text on white background can be difficult to read in case users want to use a user banner image that is white/light.
See these:
https://stackoverflow.com/questions/26189425/best-text-color-for-any-background-image  
https://graphicdesign.stackexchange.com/questions/15884/text-effect-on-any-background-color  
etc
Suggestion: `#userpage .jumbotron .mb-2, #userpage .jumbotron .font-weight-normal, #userpage .jumbotron .mt-2 { text-shadow: 1px 1px 1px #000, 1px -1px 1px #000, -1px -1px 1px #000, -1px 1px 1px #000; }`

9) Site Header, top-right corner, hover over Announcements, Guildmaster Tools, Notifications, Create Post - Text color of tooltip popup is dark on dark

10) Guild -> Guild details - Guiild name text color, depending on guild banner, text might be white on white
See example: https://www.ruqqus.com/+MGTOW
Suggestion: `#guildDetailsModal h5 { text-shadow: 1px 1px 1px #000, 1px -1px 1px #000, -1px -1px 1px #000, -1px 1px 1px #000; }`

11) In posts, guild icons should appear on the same line as the guild name. Add CSS `white-space: nowrap;`
For example see <https://www.ruqqus.com/post/12d/comment/4n9#comment-4n9>
```html
<a href="/+Quarantine">
  <img class="profile-pic-20 align-middle mr-1" src="/+Quarantine/pic/profile">
  +Quarantine
</a>```
could be
```html
<a href="/+Quarantine" style="white-space: nowrap;">
  <img class="profile-pic-20 align-middle mr-1" src="/+Quarantine/pic/profile">
  +Quarantine
</a>```
or add "nowrap" class and add CSS `.nowrap { white-space: nowrap; }` to produce same result

**Comment by jasonkhanlar** [comment]
For example at https://www.ruqqus.com/post/15t/comment/4mm?context=1

I notice that `<body id="thread">`

```css
#thread {
  background-color: #3f404a;
}
```

makes the background color appear cut off to '#3a3a3a' at the bottom if having a large Developer console open in web browser

**Comment by noahmaranesi** [comment]
I would also like to bring up the use of `prefers-color-scheme`. (Please note: I am not a web developer – I know a the basics of HTML and CSS – so terminology I use may be incorrect in future comments)

`prefers-color-scheme` basically allows websites colours to be manipulated based on the users appearance. For example, if a macOS user is in Light or Dark mode, the theme will be changed accordingly. Some sites like [DuckDuckGo](https://DuckDuckGo.com), [Twitter](https://twitter.com), [WebKit](https://webkit.org) and even GitHub use this CSS feature.

Here is some documentation:

- [Mozilla: prefers-color-scheme - CSS: Cascading Style Sheets](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme)

- [WebKit.org: Dark Mode Support in WebKit](https://webkit.org/blog/8840/dark-mode-support-in-webkit/)

- [Web.dev: Improved dark mode default styling with the color-scheme CSS](https://web.dev/color-scheme/)
