### ISSUE TITLE
Feature request Safe mode

### ISSUE THREAD

**Issue by jasonkhanlar** [ruqqus/ruqqus#153]
https://www.ruqqus.com/post/1rr

"Blur thumbnails and media preview for anything labeled NSFW (not safe for work)" - @Loonster

Also https://www.ruqqus.com/post/1rt

"NSFW guilds should auto check the NSFW checkbox by default. Even better, have it checked with a greyed out box." - @Loonster

**Comment by captainmeta4** [comment]
Auto checkbox nsfw is done.

Blurred media is WIP.
