### ISSUE TITLE
Feature request: Provide Discord-like and Twitter-like advanced search capabilities

### ISSUE THREAD

**Issue by jasonkhanlar** [ruqqus/ruqqus#155]
Allow for finding content posted to Ruqqus by advanced search queries. For example, see these provided by Discord/Twitter:

Discord allows for searching all messages by

from:username

mentions:username

has:link, embed or file

before:date

after:date

during:date

in:channel

((but it does not offer searching by quoted phrases, or even exact unquoted string/word matching)

Twitter allows for searching all messages by:

from:account

to/mentions:account (these are similar but different)

posts that have replies

posts that have links

posts with minimum quantity of replies

posts with minimum likes (upvotes/downvotes)

posts with minimum retweets

from:date

to:date

by language

hashtags

exact word matches and quoted phrases

excluding exact word matches and quoted phrases

**Comment by jasonkhanlar** [comment]
Oh, Just yestereday I noticed that I could not search for anything (not even exact string matches) if using a single or double quotation mark in the textbox for search query.

Then I noticed that I could not find a post if searching for two consecutive words that exist in a post, but the post title has additional words in between the words in the search query.

Then I noticed https://github.com/ruqqus/ruqqus/blob/master/ruqqus/routes/search.py#L27

And it seems the currently implementation for searching can used some TLC eventually.

Here are some suggested references/resources to read (I'm reading these too):

https://www.postgresql.org/docs/10/datatype-textsearch.html

https://www.postgresql.org/docs/9.6/functions-textsearch.html

https://www.compose.com/articles/mastering-postgresql-tools-full-text-search-and-phrase-search/

Full Test searching with SQLAlchemy resources:

https://stackoverflow.com/questions/13837111/tsvector-in-sqlalchemy

https://hamon.in/blog/sqlalchemy-and-full-text-searching-in-postgresql

https://sqlalchemy-searchable.readthedocs.io/en/latest/

https://readthedocs.org/projects/sqlalchemy-searchable/downloads/pdf/latest/

https://www.reddit.com/r/flask/comments/cvl9ue/af_has_anyone_found_a_simple_to_use_full_text/

**Comment by captainmeta4** [comment]
On the wish list already
