### ISSUE TITLE
Request: Consider handling invalid URLs, especially in case of unintentional mistakes, typos

### ISSUE THREAD

**Issue by jasonkhanlar** [ruqqus/ruqqus#159]
I accidentally left in a > at the end of URL in this post: https://www.ruqqus.com/post/2m2/comment/75c?context=1

I was copying/pasting it from using it elsewhere with markdown < and > to prevent auto embed from appearing

But those characters are not valid in URLs anyway. See these:

https://perishablepress.com/stop-using-unsafe-characters-in-urls/ (this is safe to read, but please exude extreme caution and wear appropriate protective gear because there is a spelling mistake in the h3 header below [character-encoding-chart](https://perishablepress.com/stop-using-unsafe-characters-in-urls/#character-encoding-chart) )

https://www.ietf.org/rfc/rfc3986.txt

https://www.ietf.org/rfc/rfc1738.txt

https://rgxdb.com/r/2MQXJD5 URL > Valid URL (RFC 3986) 
https://rgxdb.com/r/5JXUI5A2 URL > Valid URL (RFC 3986) (Advanced) 

Also see https://news.ycombinator.com/item?id=7928968

Suggestion: Maybe provide a warning notice to appear if the URL specified is invalid, that way in case anyone genuinely needs to submit a URL that is able to be visited if only breaking RFC 3986, and there's no way to access a page otherwise, that it will still be possible to link to URLs without URL encoding the unsafe characters.

**Comment by captainmeta4** [comment]
> On two occasions I have been asked, 'Pray, Mr. Babbage, if you put into the machine wrong figures, will the right answers come out?' I am not able rightly to apprehend the kind of confusion of ideas that could provoke such a question.
> -Charles Babbage
