### ISSUE TITLE
I think the UL tag is having difficulties when used in replies

### ISSUE THREAD

**Issue by stephantual** [ruqqus/ruqqus#161]
See https://www.ruqqus.com/post/2ph/comment/7gn#comment-7gn 

Tried using * and - , tried using carriage returns or just line breaks... coudln't get it to display things as a 'UL' type list. 

Shout if you need more info.

**Comment by jasonkhanlar** [comment]
I think this is fixed now? If I remember, as of earlier today, this was a dark mode CSS issue

https://discordapp.com/channels/599258778520518676/599258778520518678/688572941943963681

https://cdn.discordapp.com/attachments/599258778520518678/688572941742506052/Screen_Shot_2020-03-14_at_9.22.43_PM.png

Maybe push CTRL+SHIFT+R to reload and clear cache

**Comment by stephantual** [comment]
Ah yes, thank you.
