### ISSUE TITLE
The 'browse guilds' page doesnt' show all guilds

### ISSUE THREAD

**Issue by stephantual** [ruqqus/ruqqus#166]
https://www.ruqqus.com/browse is showing a very small number of guilds. 
+left is absent for example. 

There is no next/previous button to indicate there are more guilds to choose from, making the site look smaller than it actually is (and making it impossible to know certain guilds exist)

**Comment by jasonkhanlar** [comment]
Oh, are you sure about this/ At the very bottom I see Prev/Next buttons

Here is page 2:

https://www.ruqqus.com/browse?sort=trending&page=2 (with default sort "trending")

https://www.ruqqus.com/browse?sort=new&page=2

https://www.ruqqus.com/browse?sort=subs&page=2

**Comment by stephantual** [comment]
Thanks! Can you implement 'infinite scrolling' on this page to make it more evident? thank you

**Comment by captainmeta4** [comment]
infinite scrolling is on the wish list; there is some groundwork we have to lay to support it first.

**Comment by noahmaranesi** [comment]
> There is no next/previous button to indicate there are more guilds to choose from

@stephantual 

Hmm, I can definitely see the **Prev** and **Next** buttons at the end of each 25 Guilds shown. [It's also being shown via Archive.org](https://web.archive.org/web/20200617100736/https://ruqqus.com/browse), leading me to believe that you may of missed it, or some extension (adblocker) may be hiding it.
