### ISSUE TITLE
Request: Allow a way for users to post and link to HTTP (and not HTTPS) URLs

### ISSUE THREAD

**Issue by jasonkhanlar** [ruqqus/ruqqus#172]
See https://www.ruqqus.com/post/3kv

In this post you can see that the poster tried to link to:

http://www.cuzzblue.com/2020/03/trump-acknowledges-ancient-persian.html

but that Ruqqus automatically converted the URL to:

https://www.cuzzblue.com/2020/03/trump-acknowledges-ancient-persian.html

**Comment by captainmeta4** [comment]
For security, safety, and privacy reasons, we force HTTPS on all content submitted to Ruqqus.
