### ISSUE TITLE
Suggestion: implement flair or 'tags' - very important as GMs have very limited powers

### ISSUE THREAD

**Issue by stephantual** [ruqqus/ruqqus#173]
By forcing 'tags' or 'flairs' , and letting the GMs both edit the list (and only gms) AND retagging a post, you would make it a lot easier for the site to operate censorship free.

- it would allow GMs to tag something 'unreliable source' for the material that's no invalid enough to be sent back to +general but not confirmed enough to be confortable on the guild page (for example, rumors coudl be a tag for just that. 

- It would allow to break down a guild in subcategories without having to create a new guild (animal crossing new horizon could be a 'new horizon' tag on the 'animal crossing' guild

**Comment by captainmeta4** [comment]
On our own wishlist. Don't have an ETA right now though.
