### ISSUE TITLE
Suggestion : Lock Dark Mode to User, Not Browser

### ISSUE THREAD

**Issue by sicXnull** [ruqqus/ruqqus#182]
Looks like Dark Mode is only saved and remembered on a browser level, via cookie. 

Recommend locking it to the user instead. so when signing in on a different browser, the user does not have to re-enable. 

Small issue, but will match the other platforms who handle it this way.

**Comment by arkit3kt** [comment]
As things stand for now we're going to continue with using just the toggled and allow users to select which mode they want to use per browser. Since it's just a toggle it's not too much of an issue right now to switch between modes.
Appreciate the feature request, thanks for the suggestion.
