### ISSUE TITLE
Regarding bans from Ruqqus.com

### ISSUE THREAD

**Issue by jasonkhanlar** [ruqqus/ruqqus#189]
I was just banned from Ruqqus.com website and also Ruqqus Discord server, but I don't see a way to find any information indicating how or why I was banned.

Is there any way I can contact any humans to discuss what just happened and identify how or why I was banned?

I can also discuss at https://www.reddit.com/r/RuqqusUserGroup/ if helpful as well.

Is there any way for users to appeal bans?

**Comment by jasonkhanlar** [comment]
Wait, what?  https://ruqqus.com/post/6th this post is why I was banned?

This is NOT even doxxing!  I was discussing linking to another user that was banned who also was not doxxing, since the Reddit Internet user Bardfinn publicly lists their full name on Reddit, on their Reddit profile! Bardfinn names themself! How is that doxxing? I didn't even add any new information or say anything to dox anyone? Also, again, I don't see any indication in the Ruqqus Terms of Service or Content Policy indicating that documenting things or doxxing things is against ToS/CP. How do users appeal Ruqqus.com bans and Ruqqus Discord server bans?

**Comment by jasonkhanlar** [comment]
You can see https://imgur.com/a/TS9KCOI screenshots showing that they post their name on Reddit! How is this doxxing in any way if the user makes their name public? I am so confused!

**Comment by jasonkhanlar** [comment]
Also, I was trying to address this about the other user getting banned for the same ridiculous reason, but instead of discussing it, and intentionally ignoring it, now you ban me claiming that I doxxed someone too? This is absurdly ridiculous!!!!!!!!

**Comment by jasonkhanlar** [comment]
Also, neither the Terms of Service nor the Content Policy indicates anything about doxxing as being a bannable offense. How is it that you are intentionally avoiding to discuss these things, and then attempting to discuss it in a post that also mentions the person's name, pointing out that they make their name public...  Oh my suck!

This is more ridiculous than getting deplatformed for mentioning Eric Ciaramella's name!

**Comment by jasonkhanlar** [comment]
No user should ever be treated in this way, especially when they are trying to point out that something is NOT doxxing, but for some reason Adam (captainmeta4) is treating it as such, and it seems now that he is (and was) intentionally avoiding to discuss that too, amongst a few other things, as if to make it go away, and if I persist too much, which seems to be the case now, that I get banned for the same reason? What? This is incredibly unfortunate behavior. How can I appeal? How come I don't even have any automated email message to inform me that my account was just banned/terminated/deplatformed?

**Comment by jasonkhanlar** [comment]
https://ruqqus.com/@jasonkhanlar

Also archived at https://archive.org/ and https://archive.today/ a little less than an hour ago, and again just now, and I see that the banned page was edited/updated, to reflect that there is a message now, which didn't exist previously. Now there is a claim that I allegedly violated the rules, linked to https://archive.vn/o/pfsmC/https://ruqqus.com/help/terms which still does NOT indicate anything about doxing!  How is it possible that I violated the rules? Are you updating the rules now to add rules after banning me to then manufacture these things after the fact as part of script flipping to rewrite history? :(

**Comment by jasonkhanlar** [comment]
Also, why would you ban me from the Ruqqus Discord server at the same moment that you ban my account from Ruqqus.com? Why would you prevent me from having a voice to discuss with the Ruqqus community in the Discord server too? That seems even more worrisome than simply banning from Ruqqus.com only. Why divide and conquer users? What is the purpose/reason/agenda for that type of treatment?

**Comment by jasonkhanlar2** [comment]
It appears that captainmeta4 edited my main comment to hide the entire contents of the message for some reason.

Also I am banned from this repo on my primary GitHub account, and likely this one too.

Everyone can potentially see what my original post was here:

http://web.archive.org/web/20200413223309/https://github.com/ruqqus/ruqqus/issues/189

and here

http://archive.vn/https://github.com/ruqqus/ruqqus/issues/189

I can also discuss at https://www.reddit.com/r/RuqqusUserGroup/ if helpful as well.

Also, if I understand correctly, there is quite a significant effort to flip the script as to what is happening, and far worse than I imagined.

Creating a social media platform disguising it as a free speech platform but then incredibly engaging in some extremist anti-free-speech that is concealed by flipping scripts to rewrite history to fit character assassinate users in potentially defamatory ways seems more concerning than what I thought was just a series of petty mistakes in poor judgment.

This Ruqqus.com platform almost seems entirely like a predatory scam phishing operation, and disguising it as an open source project, but really it's maybe not so open source after all, especially given the prioritized focus on not only closing this issue, but editing my original message as if to conceal what I had stated as if there is no way anyone could see what it was that was posted.

Ah well.

Again, feel free to check out https://www.reddit.com/r/RuqqusUserGroup/.

It seems like Reddit may actually offer a LOT better quality and value of free speech than Ruqqus is able to offer, especially as it relates to Ruqqus not only having no appeal process whatsoever for bans, Ruqqus having no indication as to why a user is banned, no automated email, leaving the user to figure out for themselves why they are banned, and when they do, when they try to discuss it, they are treated more and more as a threat, and other persons who become aware of what is happening are also kicked and banned from the Discord server and maybe even also the Ruqqus.com walled garden platform. These techniques/strategies at free speech social media platform seem incredibly concerningly manipulative and maybe even possibly malicious? Why else would captainmeta4 edit my message to change its contents?

Note: I'm also archiving this again right after posting this.

**Comment by captainmeta4** [comment]
@jasonkhanlar @jasonkhanlar2 You were banned from the platform because you couldn't follow the few rules that we do have. You have broken our terms of service on multiple occasions and we are now eliminating you from the platform. This is not a discussion, a debate, or a negotiation. There is nothing to argue or plead. You are no longer welcome on Ruqqus - end of story.
