### ISSUE TITLE
Ruqqus API

### ISSUE THREAD

**Issue by dubbadhar** [ruqqus/ruqqus#206]
When can we expect a Ruqqus API? I really want an app for it, and even interested to make an open-source one myself since I'm too tried of reddit

**Comment by kek7198** [comment]
Our API is still being developed but we would eventually like to make it public :)

**Comment by dubbadhar** [comment]
sure @kek7198 , after it gets over ill start working on my private app for this 
its a great platform overall, but is a bit slow (im from india) and thats completely understandable

**Comment by kek7198** [comment]
Sounds good. We recently scaled our backend services to improve load times.

**Comment by dubbadhar** [comment]
any updates @kek7198 ? Once again, you all are doing a pretty good job

**Comment by captainmeta4** [comment]
In progress. Scaling has taken up most of my time but it's 3rd on my priority list at the moment.
