### ISSUE TITLE
Are there installation and usage tutorials?

### ISSUE THREAD

**Issue by heidongwang** [ruqqus/ruqqus#208]

**Comment by kek7198** [comment]
pinging @captainmeta4

**Comment by heidongwang** [comment]
@kek7198 

> pinging @captainmeta4

Sorry, I don't know what you mean. Could you explain it?
I want to install ruqqus on my server, but I can't find any tutorials.

**Comment by sfwr** [comment]
Running it locally is pretty difficult at the moment, lots of things to reverse engineer.  

Is redis required?  What env variables have to be set?  I assume we run it with either flask or gunicorn.

I'll take a stab at it, but it would be much easier for @captainmeta4 to provide basic instructions, I think.

**Comment by sfwr** [comment]
I got pretty far, and I'm willing to put up a PR once I have it working, but I think it's practically impossible to set up at the moment.  The schema dump is out of date, and I get errors if I just try to generate the schema out of the sqlalchemy object definitions.

**Comment by NigiriDent** [comment]
https://github.com/ruqqus/ruqqus/pull/212
