### ISSUE TITLE
Request: Make donate button/url more obvious.

### ISSUE THREAD

**Issue by Dynamic-Gravity** [ruqqus/ruqqus#209]
Please make the donate button/url more obvious as it is difficult to find this information both on this project page and on the website.

A simple link in the readme would help suffice for now.

https://ruqqus.com/help/donate

**Comment by kek7198** [comment]
I'm a bit hesitant about having an obtrusive donate button somewhere else on the page than the sidebar. The readme could be improved in this regard though.
