### ISSUE TITLE
bio doesn't support new lines

### ISSUE THREAD

**Issue by RedstonekPL** [ruqqus/ruqqus#213]
I have 2 lines in my bio
[here's how it looks like](https://i.imgur.com/gqqQg1V.jpg)
and on profile it shows up like [this](https://i.imgur.com/gTAjDbm.jpg)
and I have an idea that it could look like [that maybe](https://i.imgur.com/WfnycQ5.png)

you probably would need to set a limit of like max 3 empty lines, because otherwise there would be bios of 280 empty lines

**Comment by kek7198** [comment]
Add an extra line in between those two.

**Comment by RedstonekPL** [comment]
> Add an extra line in between those two.

doesn't work

**Comment by kek7198** [comment]
https://i.imgur.com/TYcJpv2.png

Works for me?

**Comment by RedstonekPL** [comment]
ok nvm needed to put another newline....
