### ISSUE TITLE
empty comment

### ISSUE THREAD

**Issue by RedstonekPL** [ruqqus/ruqqus#218]
https://ruqqus.com/post/eek/credit-where-its-due-rstarterpacks-top/pys

I posted an empty comment

**Comment by NigiriDent** [comment]
I reproduced this locally. It seems like it's gonna need some extra validation.

**Comment by captainmeta4** [comment]
Technically not a problem. `#  ` is valid markdown and it would be more trouble than it's worth to fix.

(You can make empty comments on reddit too)
