### ISSUE TITLE
Thread Archiving

### ISSUE THREAD

**Issue by 47773838382882828** [ruqqus/ruqqus#219]
You don't really want users to comment on year old posts as this would make them vulnerable to spam. They also serve as a good archive of "history".

So I've got a good idea.

After 150 days or so, all comments that are 150 days old are archived. If a comment was only 100 days old, it'll be open for 50 more days. Then if someone else comments on that comment the timer is again reset ONLY ON THAT comment.

This way we can allow users who take a long time to come back to post and it allows old threads to be discoverable and commentable.

**Comment by captainmeta4** [comment]
Right now posts and their associated comments archive when the post is 180days old.

While it could be per-comment, having some content on a page be archived and other content not be, would be unintuitive.

**Comment by salif** [comment]
Archiving old posts is not free speech! This is against the free speech! I have comments on 12 years old videos on Youtube and it's fucking beautiful to answer so old posts! I want to have the ability to answer old posts! Please remove that archiving! Or at least increase the time to 5 years or something!
