### ISSUE TITLE
Unexpected comment behaviour within deleted posts

### ISSUE THREAD

**Issue by ruqqusshill** [ruqqus/ruqqus#220]
It looks like comments can't be deleted by the person who made them after the OP deletes their post. 

If a user goes to a comment from either their profile history or the post's comment section - the three dot menu where "delete" normally shows has only the option "context" and "delete" is missing.

https://i.imgur.com/b6GhAV3.jpg

There is also something which another user helped confirm but we do not know if it's working as intended; - When a post is deleted by the OP, no more comments can be added (the comment submission box is hidden) but new comments can still be added if a user replies to a direct reply in the comments section. 

https://ruqqus.com/post/gv9/test-replies

Is the intended behaviour that the comments section should be locked to additional comments after a post is deleted?

**Comment by captainmeta4** [comment]
Investigating

**Comment by captainmeta4** [comment]
this was fixed
