### ISSUE TITLE
Post formatting buggy, specifically on newlines

### ISSUE THREAD

**Issue by marchkarcz** [ruqqus/ruqqus#231]
### What I sent (and seems to still be there):
Oops I forgot to respond back after I transferred the screenshots-LOL my bad. Turns out I don't have any screenshots of the thread, howvver I have some screenshots that may be beneficial in some way, so I'll leave them here
https://i.imgur.com/lTDNz9A.jpg
https://i.imgur.com/LJV8Tn2.jpg
https://i.imgur.com/nS6kRH0.jpg
https://i.imgur.com/deNOs1W.jpg
https://i.imgur.com/duJagXs.jpg - kinda just an edgy thing I saved, I forgot if this was on DeuxRAMA though

Most of these screenshots were taken a day before. The "racist" one was not taken by me.
I'll keep looking but I doubt I have screenshots of the thread; hopefully someone took a cap or archived it in some way.

### How it came out:

Oops I forgot to respond back after I transferred the screenshots-LOL my bad. Turns out I don't have any screenshots of the thread, howvver I have some screenshots that may be beneficial in some way, so I'll leave them here https://i.imgur.com/lTDNz9A.jpg https://i.imgur.com/LJV8Tn2.jpg https://i.imgur.com/nS6kRH0.jpg https://i.imgur.com/deNOs1W.jpg https://i.imgur.com/duJagXs.jpg - kinda just an edgy thing I saved, I forgot if this was on DeuxRAMA though

Most of these screenshots were taken a day before. The "racist" one was not taken by me. I'll keep looking but I doubt I have screenshots of the thread; hopefully someone took a cap or archived it in some way.

Comment: https://ruqqus.com/post/gtf/rdeuxrama-has-been-banned-second-sub/wus

**Comment by captainmeta4** [comment]
Two newlines to make a paragraph break. More info: https://ruqqus.com/help/formatting
