### ISSUE TITLE
Two issues I've run into today.

### ISSUE THREAD

**Issue by thellllvirtuoso** [ruqqus/ruqqus#233]
[bugs.zip](https://github.com/ruqqus/ruqqus/files/4777563/bugs.zip)

When I click a post and then upvote it, and then go back a page, it doesn't visually update the fact that I already upvoted the post. I'd have to reload the page to see that. Secondly, when I search for something in the search bar, I get an "Internal Server Error".

uploaded a zip file that has a screen recording of what happened.

**Comment by kek7198** [comment]
This was due to the major server outage we experienced. It should be fixed now.
