### ISSUE TITLE
Site is extremely slow 

### ISSUE THREAD

**Issue by shamilovtim** [ruqqus/ruqqus#234]
Has anyone been able to diagnose where the site slowness is coming from? Is it the db queries? Hardware? IO of the web server? I just worry that if the problem continues as it stands that the site cannot grow under these kinds of conditions. Most loads are taking 10+ seconds for me. There's some data out there that says for every X seconds of loading you lose Y amount of users. In one statistic I've found 50% of users will leave a site that takes more than 3 seconds to load. 

https://unbounce.com/landing-pages/7-page-speed-stats-for-marketers/
https://www.thinkwithgoogle.com/marketing-resources/data-measurement/mobile-page-speed-new-industry-benchmarks/

**Comment by shamilovtim** [comment]
06/15 5:24pm EST crashing again. unable to open the [roadmap post](https://ruqqus.com/post/9is/ruqqus-summer-road-map) which has 153 comments. some other meanwhile, [other posts with less comments](https://ruqqus.com/post/he8/much-better-feeling) will open just fine. a post with very few comments opens quite quickly. it seems there's a problem with your comments belonging to a post relational query.

I see you're using an ORM. have you looked into the N+1 problem yet?

**Comment by shamilovtim** [comment]
06/16: ddos protection is making the site incredibly difficult to use. constantly get redirected to cloudflare CAPTCHA. i don't think the site is being ddosed. i think either the DB queries and/or server io are suffering at scale.

**Comment by captainmeta4** [comment]
https://ruqqus.com/post/ilf/state-of-porpl-nation-ruqqus-and

**Comment by shamilovtim** [comment]
There is a lot of friction to use the site due to the DDOS protection. Need to pass several captcha before getting in every 30 minutes or so. Is there a plan to turn this off?

**Comment by shamilovtim** [comment]
Yo @captainmeta4 the Cloudflare DDOS protection is so extremely aggressive and it's making the site extremely unusable. Have you considered moving to a cloud host that offers DDOS protection baked in rather than needing it provided by Cloudflare? I know DigitalOcean does some very innovative stuff with their server products.

**Comment by captainmeta4** [comment]
Lots of improvements banged out over the course of the last week so speed should be less of an issue for the time being.

**Comment by shamilovtim** [comment]
Site feels like it's almost completely down now. Just stops at DDOS protection and never enters.
