### ISSUE TITLE
Redirect back to the entire discussion after a content submission

### ISSUE THREAD

**Issue by shamilovtim** [ruqqus/ruqqus#235]
After submitting a comment the user is redirected to the permalink for his comment. There's no reason to do this. **Instead redirect back to the thread itself.** 

1. It taxes the server with another GET request
2. the user then has to go back to the thread, using another GET reques
3. there is user frustration from this interaction, especially given current loading times / slowness

**Comment by kek7198** [comment]
We are working on solving this with the vue update.

**Comment by shamilovtim** [comment]
For now still using SSR you can probably just redirect back to the thread rather than the permalink and it will save one GET request and user click

**Comment by captainmeta4** [comment]
Coming in next minor update

**Comment by captainmeta4** [comment]
Fixed in PR #211
