### ISSUE TITLE
Remove 1rem bottom margin on comments

### ISSUE THREAD

**Issue by shamilovtim** [ruqqus/ruqqus#236]
Before:
<img width="893" alt="Screen Shot 2020-06-15 at 12 56 40 AM" src="https://user-images.githubusercontent.com/3495974/84619488-375d8700-aea3-11ea-8b6d-c16cb5725d38.png">

After:
<img width="877" alt="Screen Shot 2020-06-15 at 12 57 01 AM" src="https://user-images.githubusercontent.com/3495974/84619490-3af10e00-aea3-11ea-97e3-5f59348218da.png">

**Comment by kek7198** [comment]
The reason there is a bottom margin is that the text is wrapped inside a <p> tag.
