### ISSUE TITLE
Embed images for image post rather than requiring the link to be clicked on

### ISSUE THREAD

**Issue by shamilovtim** [ruqqus/ruqqus#237]
Currently a post which is an image must be clicked on. 

1. Poor UX / user frustration due to an extra click
2. Causes an extra GET request when the user inevitably has to click back on their browser to get back to the post

Embed the image inline in the post so it doesn't have to be clicked on. Might get tricky for e.g. an Imgur type service but regardless needs to be done and will save resources

**Comment by kek7198** [comment]
Noted. Currently, we support expanding images for i.ruqqus.com, i.imgur.com, and GIPHY images.
