### ISSUE TITLE
Bug: title bar on user settings

### ISSUE THREAD

**Issue by tobya989** [ruqqus/ruqqus#240]
On the title bar under user settings (on dark mode at least) has a comma before the Early Adopter title, and is part of the title: 
![0DCDA768-589B-4840-9DF6-C320FB46D2B9](https://user-images.githubusercontent.com/23141076/84711062-659f9d00-af5d-11ea-9fb7-f3eefd8a4c62.png)

For reference ^ :)

Gonna take a look tomorrow at it and make a PR to see what it’s affecting (might be a string or DB thing)👍

**Comment by kek7198** [comment]
It's intentional and part of the title.
