### ISSUE TITLE
Feature request: join guilds directly from All or Trending

### ISSUE THREAD

**Issue by selplacei** [ruqqus/ruqqus#242]
The All and Trending tabs are great ways to discover new communities. When seeing a community that a user definitely wants to be part of, it's much easier to do it directly from there - no need to open a new tab and load an entire page. As a new user, I found myself opening up to 5 tabs simultaneously just to click "Join" and immediately close them. This feature could be implemented as an additional button that only appears in /all, or it could mimick RES where clicking on a guild name opens a small pop-up with general information and the option to join or go to the guild's main page.

**Comment by kek7198** [comment]
This would be a good use for popovers. A user could hover over the guild name/icon and it would show a short description and join button (AJAX so no refresh).

**Comment by captainmeta4** [comment]
Done a while ago
