### ISSUE TITLE
docs.ruqqus.com not linked from anywhere on the site

### ISSUE THREAD

**Issue by selplacei** [ruqqus/ruqqus#244]
Maybe I'm blind, but it seems that the main website never references docs.ruqqus.com in any way. This created confusion because when seeing a `docs` directory at the root of the repo that contains MD files (which get rendered by GitHub), my assumption was that GitHub is the way I'm meant to browse this documentation. Because of this, for example, relative links to other MD files are broken since they don't have the ".md" extension on the website. docs.ruqqus.com is still accessible, but that doesn't even seem intentional?..

Will that sub-domain ever get attention? Maybe it's better to limit the docs to just MD files in the repo? After all, the content is the same.

**Comment by noahmaranesi** [comment]
The current live version ([docs.ruqqus.com](https://docs.ruqqus.com)) looks barely setup probably hence why it's not linked anywhere yet on the website (it doesn't even have a HTML `title` (what shows on the tab/window) tag yet)

**Comment by captainmeta4** [comment]
It's mainly used for serving the 503 and maintenence pages.
