### ISSUE TITLE
Local env setup instructions incomplete

### ISSUE THREAD

**Issue by shamilovtim** [ruqqus/ruqqus#248]
Using macOS

1. Follow local env setup instructions
2. Navigate to http://ruqqus.localhost:8000/signup 
3. Attempt to register as name: admin // pw: password. Click submit.
4. Receive error screen: 

<img width="554" alt="Screen Shot 2020-06-17 at 5 30 53 PM" src="https://user-images.githubusercontent.com/3495974/84952661-52591280-b0c0-11ea-8eaa-528aec8b2c5e.png">
 
CORS is not functioning on a fresh env either, I had to comment it out.

```python
def no_cors(f):

    """
    Decorator prevents content being iframe'd
    """

    def wrapper(*args, **kwargs):

        origin = request.headers.get("Origin",None)

        # if origin and origin != "https://"+app.config["SERVER_NAME"]:
        #     return "This page may not be embedded in other webpages.", 403

        resp = make_response(f(*args, **kwargs))
        resp.headers.add("Access-Control-Allow-Origin",
                         app.config["SERVER_NAME"]
                         )

        return resp

    wrapper.__name__=f.__name__
    return wrapper
```

**Comment by jakemayeux** [comment]
I get the same problem, I'll look into fixing this today

**Comment by jakemayeux** [comment]
Need help troubleshooting. I'm trying to manually add a user to the database. This query will insert a user with the name `ruqqie` and password `password`. Logging in does nothing
```
INSERT INTO users (id, username, email, passhash, created_utc, creation_ip, tos_agreed_utc, login_nonce)
           VALUES (1, 'ruqqie', 'ruqqie@ruqqus.com', 'pbkdf2:sha512:150000$vmPzuBFj$24cde8a6305b7c528b0428b1e87f256c65741bb035b4356549c13e745cc0581701431d5a2297d98501fcf20367791b4334dcd19cf063a6e60195abe8214f91e8',
           1592672337, '127.0.0.1', 1592672337, 1);
```

**Comment by shamilovtim** [comment]
I think this is a good stopping off point to wait until their team addresses this

**Comment by jakemayeux** [comment]
Not sure their team will address it, the lead developer only uses a staging environment - he doesn't know how to run locally

**Comment by jakemayeux** [comment]
I suspect it is a problem with the domain. I've been getting `This page may not be embedded in other webpages.` after signup.

Also just realized I forgot a small addition to the local env instructions, making a PR to fix now

**Comment by init-i** [comment]
This same issue happened to me. The problem is ruqqus is unable to set session cookies because the SESSION_COOKIE_SECURE config flag is set to True, but you are not using HTTPS. Since you don't have any session cookies `sign_up_post` in `ruqqus/routes/login.py` aborts with a 400 status code:

```
def sign_up_post(v):
   ...
   submitted_token=session.get("signup_token", "")
    if not submitted_token:
        abort(400)
```

The easiest work around for this is to disable SESSION_COOKIE_SECURE, which you can do in `ruqqus/__main__.py`. Otherwise you need to enable HTTPS.

**Comment by jakemayeux** [comment]
This can be closed with https://github.com/ruqqus/ruqqus/pull/259
