### ISSUE TITLE
Exceeding the bio limit on your account causes a server error

### ISSUE THREAD

**Issue by GingkathFox** [ruqqus/ruqqus#255]
Issue tracker is **ONLY** used for reporting bugs.

Basically, I was a idiot and didnt see the 280 char limit under the bot, and tried to paste in my public PGP key.

## Expected Behavior

Nothig should happen except a alert stating you've exceeded the limit.

## Current Behavior

Ruqqus loads up a sever error page, screenshot below:
![Uh Oh, im stupid](https://user-images.githubusercontent.com/33764485/85187234-28dcea00-b26c-11ea-8064-47a51b271469.png)

## Possible Solution

Pretty obvious, just check the bio length before sending a request

## Steps to Reproduce

1. cram your bio with text, output from `cmatrix` in fullscreen is perfect
~~2. watch as the world burns~~

**Comment by kek7198** [comment]
Fixed
