### ISSUE TITLE
i clicked on a post and let it load, and when i came back this had happened (Screenshot attached)

### ISSUE THREAD

**Issue by GingkathFox** [ruqqus/ruqqus#262]
Issue tracker is **ONLY** used for reporting bugs.

## Expected Behavior

The post should load propery, with my dark theme setting active.

## Current Behavior

This: 
![Screen Shot 2020-06-21 at 9 23 45 PM](https://user-images.githubusercontent.com/33764485/85240314-c3246580-b405-11ea-9120-09e4b6d8a481.png)

## Steps to Reproduce

1. i guess just load up a page and switch to a different tab.
2.
3.
4.

**Comment by jesseerwin** [comment]
Looks to me like the CSS didn't load completely; probably just has to do with the downtimes happening.

**Comment by 47773838382882828** [comment]
Yeah Ruqqus is way to heavy on JS, each page is around 15 megabytes
