### ISSUE TITLE
Ranking Algorithm for hot needs a little tweaking

### ISSUE THREAD

**Issue by 47773838382882828** [ruqqus/ruqqus#269]
**Is your feature request related to a problem? Please describe.**
The problem is that 40-80% of posts in hot are from the same guild, +watchredditdie

**Describe the solution you'd like**
The algorithm needs to be more democratic to also display other guilds. The solution is to add limits to how many times a guild can appear in the page. ie don't allow more than 4 posts from +watchredditdie appear on hot (per page).

**Describe alternatives you've considered**
Leaving it alone sets a bad impression- new users won't even know other guilds exist, for me it felt like all ruqqus was, is people complaining about Reddit.

**Comment by kek7198** [comment]
We have a post and poll up regarding this issue https://ruqqus.com/post/n5y/poll-should-ruqqus-temporarily-limit-the

**Comment by 47773838382882828** [comment]
👍

**Comment by captainmeta4** [comment]
Tweaked, time penalty is now t^1.4
