### ISSUE TITLE
Feature Request: Sort by "Top: 6 Months" and "Top: All Time"

### ISSUE THREAD

**Issue by bcornw2** [ruqqus/ruqqus#272]
Currently, the max you can sort is Top: Year. Which makes sense, since Ruqqus hasn't been around for more than a year. But eventually we should be able to sort by Top: All Time, like how reddit does. Additionally, Voat has Top: 6 Months. This is hugely useful since the gap between 1 month and 12 months is quite long. I think this would be a smart feature to implement.

**Comment by captainmeta4** [comment]
You can sort by Top: All Time already:

Desktop

![](https://puu.sh/G0M6Q.png)

Mobile

![](https://puu.sh/G0M7T.png)

I could add a 6 month option though, once I find a suitable icon.

**Comment by kek7198** [comment]
Possibly. @captainmeta4 @arkit3kt what do you two think?

**Comment by 47773838382882828** [comment]
And it'd be nice to have a custom sort by date 

Such as 10-June-2019 to 14-Feb-2020
