### ISSUE TITLE
Cannot view Guild details on mobile

### ISSUE THREAD

**Issue by noahmaranesi** [ruqqus/ruqqus#274]
Currently on mobile there is no ability to view the Guild details.

All that’s needed is adding the “i” to the right side of the navigation bar (where you have the ability to sort posts and the duration filter) to show Guild details. The Guild details dialogue shows founded date, Guildmasters (**currently not clickable**), members and about (sidebar information).

**Comment by kek7198** [comment]
Good idea; I'll have to add this
