### ISSUE TITLE
If a post is yanked to a Guild, the user should have the choice of removing it from that Guild

### ISSUE THREAD

**Issue by noahmaranesi** [ruqqus/ruqqus#279]
This would be a good option for if a 'controversial' Guild was to yank it (for whatever reason) and the user does not want to be associated with it. If implemented:

- it also doesn't require the user to delete the post to remove it from that Guild.

- allow the user to prevent the post from going into that Guild again (preferably automatically enabled) after they have un-yanked it.

**Comment by kek7198** [comment]
Post authors have the ability to un-yank.

> allow the user to prevent the post from going into that Guild again (preferably automatically enabled) after they have un-yanked it.

That's a good idea. What do you think about a "disable yanking" toggle when creating a post?

**Comment by noahmaranesi** [comment]
Sorry, I wasn't aware that it's already a thing! Disable 'yanking' would be a good addition. Or even having the ability for it to be automatically accepted if the user is subscribed to that Guild? (I see how that can be a privacy issue, but if that was implemented, it could be a switchable – on, off – option)
