### ISSUE TITLE
Local development server throws AttributeError: 'NoneType' object has no attribute '_instantiate_plugins'

### ISSUE THREAD

**Issue by codeclem** [ruqqus/ruqqus#280]
Issue tracker is **ONLY** used for reporting bugs.

I've just followed the instructions in the Readme for setting up a local development server and get the following error when running the `gunicorn` command:

```
$ gunicorn ruqqus.__main__:app -w 3 -k gevent --worker-connections 6 --preload --max-requests 500 --max-requests-jitter 50
/home/clem/.local/lib/python3.8/site-packages/flask_caching/__init__.py:191: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
  warnings.warn(
Traceback (most recent call last):
  File "/usr/bin/gunicorn", line 11, in <module>
    load_entry_point('gunicorn==20.0.4', 'console_scripts', 'gunicorn')()
  File "/home/clem/.local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/home/clem/.local/lib/python3.8/site-packages/gunicorn/app/base.py", line 228, in run
    super().run()
  File "/home/clem/.local/lib/python3.8/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/home/clem/.local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 58, in __init__
    self.setup(app)
  File "/home/clem/.local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 118, in setup
    self.app.wsgi()
  File "/home/clem/.local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/clem/.local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/clem/.local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/clem/.local/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/clem/projects/ruqqus/ruqqus/__main__.py", line 87, in <module>
    "followers":[create_engine(x, pool_size=pool_size, pool_use_lifo=True) for x in app.config['SQLALCHEMY_READ_URIS']]
  File "/home/clem/projects/ruqqus/ruqqus/__main__.py", line 87, in <listcomp>
    "followers":[create_engine(x, pool_size=pool_size, pool_use_lifo=True) for x in app.config['SQLALCHEMY_READ_URIS']]
  File "/home/clem/.local/lib/python3.8/site-packages/sqlalchemy/engine/__init__.py", line 435, in create_engine
    return strategy.create(*args, **kwargs)
  File "/home/clem/.local/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 56, in create
    plugins = u._instantiate_plugins(kwargs)
AttributeError: 'NoneType' object has no attribute '_instantiate_plugins'
```

I am using Arch Linux so I used its package manager to install gunicorn, redis, and postgresql instead of brew, but the rest of the commands I entered as is with no error until gunicorn.

## Expected Behavior
A local instance of Ruqqus should run.

## Current Behavior
Python throws an error and quits.

## Steps to Reproduce
1. Follow the local development instructions in Ruqqus' readme on Arch Linux

## Context (Environment)
Arch Linux
Python 3.8.3
Postgres 12.3-2
Redis 6.0.5-1
Gunicorn 20.0.4
Ruqqus commit 23bf6a7

**Comment by Known-as-X86** [comment]
You need to install and properly configure postgres. u can test your postgres access uri with the following command "psql {{DATABASE_URI}}"

use `sudo netstat -plnt` to check if anything is listening on port `5432` that is the default for postgres

if not you need to configure the listening port and restart postgres 

### Change the following config file `/etc/postgres/{version}/main/postgresql.conf`
and uncomment/change the following lines
```
listen_addresses = 'localhost'
port = 5432  
```
### then restart postgres
`systemctl enable postgres`
`systemctl start postgres`

**Comment by codeclem** [comment]
Thanks. I have a little experience with using Postgres on side projects, so I already had it up and running with a user account, but I'm no expert so I'm probably missing something. It's running on the default port 5432 and I can connect with psql:

`
$ psql postgres

psql (12.3)

Type "help" for help.

postgres=# \du

                                   List of roles

 Role name |                         Attributes                         | Member of 

-----------+------------------------------------------------------------+-----------

 clem      | Superuser, Create role, Create DB                          | {}

 postgres  | Superuser, Create role, Create DB, Replication, Bypass RLS | {}

postgres=# 
`

And the Ruqqus schema was created no problem:

`
postgres=# \d

                List of relations

 Schema |         Name         |   Type   | Owner 

--------+----------------------+----------+-------

 public | alts                 | table    | clem

 public | alts_id_seq          | sequence | clem

 public | badge_defs           | table    | clem

 public | badge_list_id_seq    | sequence | clem

 public | badges               | table    | clem

 public | badges_id_seq        | sequence | clem

 [snip]

 public | userblocks           | table    | clem

 public | userblocks_id_seq    | sequence | clem
[snip]
`

I tried adding my username to the DATABASE_URL environment variable as you described and still get the same error.

**Comment by Known-as-X86** [comment]
I noticed someone left some heroku  related code in the master branche.

delete  line 87  on `ruqqus/__main__.py` for a quick fix. maybe @captainmeta4  can explain its usage?

**Comment by Known-as-X86** [comment]
Enjoy! :)

**Comment by codeclem** [comment]
Thanks! Now the app boots up but there's errors relating to followers (`KeyError: 'followers' amongst a bunch of exception tracebacks). Looks like I just need to wait a few commits :)

**Comment by lfleal** [comment]
If you set 'HEROKU_POSTGRESQL_CRIMSON_URL' and 'HEROKU_POSTGRESQL_BLUE_URL' to the same value of 'DATABASE_URL' you can get the app to launch

**Comment by codeclem** [comment]
Yup same here.

**Comment by Known-as-X86** [comment]
They might want to setup some scripts for deploying a local env.

The dump for postgres is apparantly outdated

`sudo -u postgres psql postgres `

and execute the following query:
`ALTER TABLE submissions
ADD COLUMN score_best int null;`

run this command for a quick fix. at this point i can;t help since the devs who know this code in and out are apparently asleep/ busy. they should

**Comment by codeclem** [comment]
Awesome!! Thanks everybody.

**Comment by Known-as-X86** [comment]
Just wait till you get the hmac error on signup ;)

**Comment by captainmeta4** [comment]
https://github.com/ruqqus/ruqqus/releases/tag/2.13.1

DB schema matching the code
