### ISSUE TITLE
make ruqqus a pwa

### ISSUE THREAD

**Issue by amazingcaio** [ruqqus/ruqqus#284]
**Is your feature request related to a problem? Please describe.**
not really. it's a bit frustrating that ruqqus isn't a progressive web app, but not a deal breaker.

**Describe the solution you'd like**
i think ruqqus should be a progressive web app, which is basically a website that behaves like an app, like being able to "install" it, having notifications, etc., so you can improve user experience and engagement on the website. plus i don't think it would be a lot of work for you to make ruqqus a pwa - you're at least half way there, as your website has a responsive design and is actually quite fast on mobile. the only two requirements for websites to be pwas are a manifest and a service worker.

**Describe alternatives you've considered**
you could decide not to, as pwas aren't mandatory. also native mobile apps are a good alternative — or maybe better, at least for some — especially for ios, as support for pwas on safari is rather lacking.

**Additional context**
for more information you could check out [this webpage](https://web.dev/progressive-web-apps/).

**Comment by Draphar** [comment]
Interesting, I would love if ruqqus had an almost entirely static (opt-in) website with as little JS as possible.

**Comment by metalsp0rk** [comment]
There are plans for an overhaul of components of Ruqqus, moving to a different frontend.  Providing PWA functionality will be a lot easier once that's done.

Regarding static site, less JS, that's the exact opposite of the intent of this request.

**Comment by 47773838382882828** [comment]
@Draphar i agree, barebones websites are better

**Comment by mkay581** [comment]
Definitely agree with this request. The web experience (especially on mobile) is super slow. Taking advantage of PWA features like service workers, local caching, etc will make the experience more snappy.
