### ISSUE TITLE
 Dark mode inconsistencies

### ISSUE THREAD

**Issue by FrenzyYum** [ruqqus/ruqqus#285]
There are various inconsistencies of dark mode compared to a default light theme.
Text color on :hover for certain attributes in dark mode is dark, making text blend with the background.
Case 1:
.table-hover tbody tr:hover in main_dark.css
![firefox_nCeI7N2I1G](https://user-images.githubusercontent.com/30303575/86115468-a8708180-bad4-11ea-888c-775723d43fe4.png)
Case 2:
a.text-gray-500:hover in main_dark.css
![firefox_MghIfX9Z8D](https://user-images.githubusercontent.com/30303575/86115469-a9091800-bad4-11ea-8ffb-e82f3a647524.png)
Case 3:
a.text-muted:hover in main_dark.css
![firefox_tq9fK1H4Hb](https://user-images.githubusercontent.com/30303575/86116591-5b8daa80-bad6-11ea-807a-8ddfe2e883f1.png)
Not sure whether there are any more inconsistencies like that but those are what I found.
As a side note, you sure you want to have dark violet for username links like this?
![firefox_TyShUGA65n](https://user-images.githubusercontent.com/30303575/86119181-af01f780-bada-11ea-9e26-0f550774ca8e.png)

**Comment by SFM61319** [comment]
Yeah, dark violet causes 2 problems:  
 - Not clearly visible on a dark background
 - Used to show *visited* links in many sites

**Comment by captainmeta4** [comment]
I think this has been fixed
