### ISSUE TITLE
Add docker-compose support for local development

### ISSUE THREAD

**Issue by nickatnight** [ruqqus/ruqqus#289]
**Is your feature request related to a problem? Please describe.**
Provisioning local development is a pretty mundane process. 15 + steps just to get a local dev env running? What if the developer doesn't want to install all those dependencies on their host environment?

**Describe the solution you'd like**
This can be easily simplified using `docker-compose` and a compose `.yml` file. eg: include a backend/redis/postgres service, along with an `.env` file with required vars. This would take at most 4 steps. One argument I see here "I need to install Docker? Eww". My response would be, why are you a developer in 2020 not using Docker lol.

**Describe alternatives you've considered**
Other alternative would be to install linux/windows vagrant box, or use a virtualenv

**Comment by lfleal** [comment]
Checkout https://github.com/ruqqus/ruqqus/pull/275

**Comment by nickatnight** [comment]
Ahh this is great! Thank you for the reference @lfleal I'll close this ticket
