### ISSUE TITLE
Ruqqus API + Dank

### ISSUE THREAD

**Issue by shirtmogul12** [ruqqus/ruqqus#292]
**Is your feature request related to a problem? Please describe.**
Dank was a reddit app developed by Saket Narayan of Square. It's pretty cool. The UI is fast, clean and inspiring. He never released it.

**Describe the solution you'd like**
With the Ruqqus API, an Android app can be developed using Dank as its foundation. Here's the source code: https://github.com/saket/Dank. 

**Describe alternatives you've considered**
The alternative would be to design an official Android app from scratch which might take a lot of time.

**Additional context**
Once the Ruqqus API is out a great Android app can be had very quickly with Dank.

**Comment by captainmeta4** [comment]
Out of scope for this repo
