### ISSUE TITLE
Option to use different/custom StyleSheets throughout the app (for an account globally)

### ISSUE THREAD

**Issue by SFM61319** [ruqqus/ruqqus#294]
Looking at [the web app](https://ruqqus.com/ "Ruqqus") and [the source code](https://github.com/ruqqus/ruqqus/ "Source Code"), one can say [Ruqqus](https://ruqqus.com/ "Ruqqus") uses [Bootstrap](https://getbootstrap.com/ "Bootstrap 4"). Although Bootstrap 4 looks good and is one of the best CSS Frameworks out there, everyone may not like it.  
  
So, it would be great if there was an option in the settings to choose between different known StyleSheets (maybe in the form of a dropdown). There are many known StyleSheets out there - [Bootstrap](https://getbootstrap.com/ "Bootstrap 4"), [Materialize](https://materializecss.com/ "Material Design"), [Foundation](https://get.foundation/ "Foundation"), [UIkit](https://getuikit.com/ "UIkit"), etc. - or even custom/user-made StyleSheets (like, for me, it is [Fluent Web](https://github.com/SFM61319/Fluent-Web/ "Fluent Web") (although incomplete), a pure CSS and JavaScript web implementation of Microsoft's Fluent Design System)  
  
Please consider this (because this might be the equivalent of [Reddit's](https://www.reddit.com/ "Reddit") option to choose color mode and theme (like dark mode with midnight color theme))  
  
Thank you!

**Comment by kek7198** [comment]
While I like the idea of themes (Tumblr, Slack, etc); we need to keep a consistent design system in place. But colors could be customizable for users, accessible in their settings.

**Comment by mnn** [comment]
I think it would be laborious to develop (different names of css classes in almost every css library, also many brings its own js) and quite a pain to maintain. In my opinion advanced users could use a browser addon for injecting styles (e.g. Stylish) or scripts (e.g. Violentmonkey).

It would be nice, if Ruqqus (the front-end) would support such endeavors (e.g. not using generated css class names or css-in-js). It's not impossible to write customizations without such support, but it's rather tedious and fragile (last time I was writing a userscript for Twitter, I had to use locating of elements by text [contents displayed to user] and relative position to other elements).
