### ISSUE TITLE
Comments: Send with "Ctrl+Enter"

### ISSUE THREAD

**Issue by jfwerner** [ruqqus/ruqqus#296]
**Is your feature request related to a problem? Please describe.**
Commenting requires moving your mouse. Unnecessary when you have a keyboard, right?

**Describe the solution you'd like**
It should be possible to send a comment with a keyboard shortcut, ideally Ctrl + Enter.

**Describe alternatives you've considered**
The other possible shortcut would be Enter, but considering the length of some conversations this would be annoying to create new paragraphs.

**Comment by kek7198** [comment]
This is a good idea. We could look into this after the vue update :)
