### ISSUE TITLE
I'll write unit tests if you dig?

### ISSUE THREAD

**Issue by richtier** [ruqqus/ruqqus#298]
**Is your feature request related to a problem? Please describe.**
Looks like no unit tests. Testing improves maintainability yada yada yada you know the drill

**Describe the solution you'd like**
I'm happy to:
- set up test framework using pytest, and flask testing library
- plug into circleci
- add code coverage badge
- write a few tests 

**Describe alternatives you've considered**
Could totally, like, not write any tests

**Comment by richtier** [comment]
@kek7198 you dig?

**Comment by penguinpowernz** [comment]
@captainmeta4  ?

**Comment by captainmeta4** [comment]
Sure. Feel free to set up and PR.

**Comment by richtier** [comment]
https://github.com/ruqqus/ruqqus/pull/326
