### ISSUE TITLE
If the user has no unread messages, automatically show the entire inbox

### ISSUE THREAD

**Issue by noahmaranesi** [ruqqus/ruqqus#299]
The current behaviour for clicking the notifications (bell) icon when there's no notifications shows a button to direct you to your full inbox.

If there's no new notifications, it may be better to automatically go to the full inbox instead.

Another note which probably doesn't matter too much, but putting in any value in `all=*` has no affect and will go to the full inbox regardless of the value. For example: https://ruqqus.com/notifications?all=false, https://ruqqus.com/notifications?all=abc123

**Comment by kek7198** [comment]
The bell does take you to the full inbox if there are no notifications.

**Comment by noahmaranesi** [comment]
Hmm that’s odd. The only reason I created this was purely because it didn’t show my full inbox when I had no notifications (it happened several times: even after reloading the page, etc). Maybe it was just a glitch.
