### ISSUE TITLE
Design and implement an "open" JSON API spec for apps and other services to connect to 

### ISSUE THREAD

**Issue by rjjakes** [ruqqus/ruqqus#300]
**Is your feature request related to a problem? Please describe.**
The problem is that to gain a critical mass of users, an iOS and Android app would be needed. I'm not sure creating a Ruqqus branded app would be the best solution for a few reasons:  
- it would need to be closed source and therefore doesn't fit the open source / decentralized spirit of this project. 
- it locks out other developers from creating better apps in the future by implying that the Ruqqus branded app is the only/correct app to use 

**Describe the solution you'd like**
A well documented, open API spec that is separate from this project (called something like "open community API spec"). Ruqqus would implement this API as part of: https://github.com/ruqqus/ruqqus/blob/master/ruqqus/routes/api/json_api.py
Apps and other services would be free to use that spec for any site that implemented it, including ruqqus.com or even any later clone sites. 

**Describe alternatives you've considered**
Creating a Ruqqus branded iOS app.

**Comment by metalsp0rk** [comment]
We are working on something to solve this problem.  You can expect the early stages of this to show up in a PR in the near future.
