### ISSUE TITLE
Allow non-english characters to be used in guild names and usernames

### ISSUE THREAD

**Issue by salifm** [ruqqus/ruqqus#301]
**Is your feature request related to a problem? Please describe.**

The problem is that currently account's usernames and guild names can't contain characters from alphabets other than Latin alphabet.

**Describe the solution you'd like**

My requst is to allow characters from other alphabets like Cyrillic, Greek, Arabic, Chinese to be used in subreddit names and usernames. And it would be better if you allow only alphabets, instead of all Unicode characters.

**Comment by salifm** [comment]
Internationalization is one of the most important reasons why Facebook and Youtube are most popular social medias in the world. Peoples across the Earth should be able to register and access content in their native language. This can make Ruqqus more popular than Reddit some day. Facebook would not be so popular if it supported only English titles for names, pages and groups.

**Comment by 47773838382882828** [comment]
It could be used to act like a different user

For example @jéff could say retarted things and impersonate @jeff

**Comment by drvladb** [comment]
I think it would be a good to allow custom character sets link Cyrillic and Chinese (not limited to) but not permit characters like é to avoid impersonation and to make putting in usernames easier.

**Comment by captainmeta4** [comment]
No, due to homograph attacks.

**Comment by salifm** [comment]
I believe that the internationalization is more important than the risk of homograph attacks and it's not difficult to prevent homograph attacks.
