### ISSUE TITLE
Feature Request: sticky sort and filter settings

### ISSUE THREAD

**Issue by dword4** [ruqqus/ruqqus#302]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
A sticky setting for the Sort and Filter options, every time I go to another guild page I have to tell it to sort by New and within the last day.

**Describe alternatives you've considered**
Some kind of browser-side method such as Greasemonkey to make the settings permenant.

**Additional context**
nope

**Comment by kek7198** [comment]
Allowing users to tweak their sort options at the guild-level would be nice. I like this idea.
