### ISSUE TITLE
Guilds in the sidebar should be alphabetized

### ISSUE THREAD

**Issue by im4potato** [ruqqus/ruqqus#312]
**Is your feature request related to a problem? Please describe.**
Guilds in the sidebar should be alphabetized, currently they show up in the order that you joined them in, which gets harder to navigate as you add more.

**Describe the solution you'd like**
Being alphabetized by default would be best, but it would be nice to have different sorting options, such as activity or users.

**Comment by kek7198** [comment]
Custom guild sorting in the sidebar is something I'm working on with vue.js (draggable.js).
