### ISSUE TITLE
Add a "Save Post/Comment" feature

### ISSUE THREAD

**Issue by Wingo5315** [ruqqus/ruqqus#313]
**Is your feature request related to a problem? Please describe.**
I find a comment/post that I like, but there isn't a way to save it for me to read later.

**Describe the solution you'd like**
I would like a "Save Post/Comment" solution similar to Reddit's, but also with the ability to download saved posts/comments as a JSON, TXT or HTML file.

**Describe alternatives you've considered**
I've considered bookmarking every single comment, but not all users will want to or be able to do this. The amount of bookmarks would get rather messy after a while.

**Additional context**

**Comment by kek7198** [comment]
Content saving is something we'd like to add :)

**Comment by Trey50Daniel** [comment]
Could this not be handled as a sort of "Bookmarks" section similar to the way that Twitter handles tweets that users want to save for future viewing?

**Comment by Wingo5315** [comment]
@Trey50Daniel There isn't that much of a difference between Twitter's Bookmarks feature and Reddit's Save Post/Comment feature, so yes. But I think the ability to download saved posts/comments as a JSON/HTML/TXT file should also be included.

**Comment by captainmeta4** [comment]
coming with vue if not sooner
