### ISSUE TITLE
Guild listing APIs are broken

### ISSUE THREAD

**Issue by Dog2puppy** [ruqqus/ruqqus#314]
Issue tracker is **ONLY** used for reporting bugs.

The guild listing APIs return a 500 error. 

## Expected Behavior

The API endpoint should return JSON of recent posts

## Current Behavior

The API endpoint gives a 500 error

## Possible Solution

not sure

## Steps to Reproduce

1. Visit https://ruqqus.com/api/v1/guild/Ruqqus/listing
2. See the 500 error

## Context (Environment)

I can't make RuqqusBot show recent posts because of this. 

The guild listing API endpoint is in a non functioning state. 

## Detailed Description

The guild listing API should not return a 500 error. 

## Possible Implementation

Use the logs to figure out why it is broken.

**Comment by salifm** [comment]
It works for me, without error

**Comment by captainmeta4** [comment]
Works now
