### ISSUE TITLE
Make ruqqus.com/@me redirect to your own profile

### ISSUE THREAD

**Issue by Xeoth** [ruqqus/ruqqus#316]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When visiting https://ruqqus.com/@me, the site should redirect to your own profile.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by Xeoth** [comment]
I can try and do it if you don't have anything against it.

**Comment by Steampunkery** [comment]
We have https://ruqqus.com/me which is pretty close

**Comment by captainmeta4** [comment]
https://ruqqus.com/me
