### ISSUE TITLE
Selecting a post should require clicking on the text, and not include the whitespace after

### ISSUE THREAD

**Issue by im4potato** [ruqqus/ruqqus#319]
**Is your feature request related to a problem? Please describe.**
I often use middle click to turn on auto-scroll to browse, but because the clickable area for each post is so large you have to be very aware of where you middle click, otherwise it leads to a new tab being opened accidentally.

**Describe the solution you'd like**
Links should only be clickable on the text itself, not the whitespace.

**Comment by kek7198** [comment]
We use Bootstrap stretched-links to make the clickable area larger so it's easier to navigate to a post rather than having to click a tiny, specific link.
