### ISSUE TITLE
Replace Schema.txt with Alembic

### ISSUE THREAD

**Issue by Korkd** [ruqqus/ruqqus#321]
**Is your feature request related to a problem? Please describe.**
Currently, the schema of the db is tied to a generated SQL file. This makes it difficult to maintain a local db when changes are introduced. It also makes it difficult to submit changes to the database schema.

**Describe the solution you'd like**
Replace the flat file with [alembic](https://alembic.sqlalchemy.org/en/latest/tutorial.html) change management.

**Comment by Korkd** [comment]
Started looking over this to see how hard it'd be and noticed a lot of duplicate indexes. Submissions table is particularly bad:

```
    "domain_ref_idx" btree (domain_ref)
    "post_18_index" btree (over_18)
    "post_author_index" btree (author_id)
    "post_offensive_index" btree (is_offensive)

    "submission_domainref_index" btree (domain_ref)
    "submissions_author_index" btree (author_id)
    "submissions_offensive_index" btree (is_offensive)
    "submissions_over18_index" btree (over_18)
```

I've seen it on several other tables but guessing this is a mistake and there isn't some crazy magic going on that involves duplicate indexes being needed?

Other concern is there is some inconsistency in how score is treated in the db. Some score fields are floats while others are integers. e.g. from submissions:

```
 score_hot         | double precision       |           |          | 0
 score_top         | integer                |           |          | 0
 score_activity    | double precision       |           |          | 0
 score_disputed    | double precision       |           |          | 0
```

**Comment by Korkd** [comment]
Decided to implement it as I was trying to troubleshoot running ruqqus locally anyways.

**Comment by captainmeta4** [comment]
Would be happy to review a PR for this, I hate keeping schema.txt up to date.
