### ISSUE TITLE
Adding an application and OAuth system for User Accounts

### ISSUE THREAD

**Issue by drvladb** [ruqqus/ruqqus#322]
**Is your feature request related to a problem? Please describe.**
As a developer I have to use user account credentials Ex (using RuqqusAPI python Library)
ruqqus = RuqqusAPI("myemail@gmail.com", "SuperSecritPassword")

**Describe the solution you'd like**
Write a system for apps to request permission for example "Ability to Upvote" or "Join Guilds" that app or program developers can use to get access to user accounts.

**Describe alternatives you've considered**
Users would not be conformable providing credentials to a "Untrusted" third party.

**Additional context**
Also, Provide an ability to see which apps are connected and what they can do.
IE:
![image](https://user-images.githubusercontent.com/33793511/87263132-2c8a1800-c48a-11ea-8c0f-237a585ca3c6.png)

**Links**
[OAuth](https://en.wikipedia.org/wiki/OAuth)

**Comment by drvladb** [comment]
I can write portions of the code necessary for this, just want to make sure that this would be good to work on

**Comment by captainmeta4** [comment]
On the roadmap: https://ruqqus.com/post/yvw/ruqqus-backend-roadmap-task-list

**Comment by lithiumjs** [comment]
Done in #404.
