### ISSUE TITLE
Add Localization

### ISSUE THREAD

**Issue by Wasps0** [ruqqus/ruqqus#323]
Potentially make it so we can do it ourselves as a community project.

**Comment by Spayco** [comment]
would help in arabic

**Comment by drvladb** [comment]
Possibly establish a locale system and create a [crowdin](https://crowdin.com/) like system to translate Ruqqus to help outreach into communities with other languages. There are good examples of large non us communities (like /r/de), plus this wouldn't be really hard to make

**Comment by salifm** [comment]
I can help for bulgarian translation

**Comment by WaspMXL** [comment]
A locale system with .POT(source) and .PO(translation) could work. They are both GNU and easy to use. You can compile them into .MO but you can also parse them directly with ```polib```
Sources [https://stackoverflow.com/questions/9580449/parsing-gettext-po-files-with-python](url)
