### ISSUE TITLE
Politics Filter

### ISSUE THREAD

**Issue by hcars** [ruqqus/ruqqus#325]
**Is your feature request related to a problem? Please describe.**
The +All table has a lot of political content, and many users aren't always in the mood for politics all the time.

**Describe the solution you'd like**
I would like button that filters political content out of trending and all. Tagging posts as political would work the same as it does for NSFW.

**Describe alternatives you've considered**
Only viewing one guild at a time that is apolitical, or viewing the guilds I'm in only.

**Additional context**

**Comment by dginovker** [comment]
Would guilds sign up to be politically-based guilds, and the admins can overturn it, or did you have something else in mind?

**Comment by drvladb** [comment]
@dginovker If you submit a post that involves politics it should be tagged as “political” by you or the mods of the guild

**Comment by hcars** [comment]
> 
> 
> @dginovker If you submit a post that involves politics it should be tagged as “political” by you or the mods of the guild

@dginovker That is what I was thinking, but guilds registering as political could also work.

**Comment by kek7198** [comment]
Leaving people to decide whether something is political is difficult. It varies from person to person and isn't clear cut as something like "not safe for work".

If were to develop a logical checklist to determine if something is political, what would that look like?

**Comment by drvladb** [comment]
My guess that a checklist would look like (not complete):

1. Does this post contain mentions political figure 
2. Does this post link to a webpage of a political figure
3. Does this post link to a news page about politicians
4. Does this post mention a political party

**Comment by captainmeta4** [comment]
Added
