### ISSUE TITLE
Links are displayed differently in comments, whether they're "www" or "https" 

### ISSUE THREAD

**Issue by dginovker** [ruqqus/ruqqus#327]
**Is your feature request related to a problem? Please describe.**
[Particularly](https://i.imgur.com/feYqx0c.png) on dark mode, some links that are embedded in text are almost impossible to see

**Describe the solution you'd like**
All links should appear the same color as "www" ones, regardless of whether or not they start with "https"

**Note**
This issue was originally a complaint about links not being clear - but it seems the root cause is links are different colors depending on their prefix.

**Comment by dginovker** [comment]
For some reason, some links appear very clearly: 
![image](https://user-images.githubusercontent.com/32943174/87479225-164e9a00-c5f9-11ea-9efd-f1850a04e3a9.png)

While some don't:

![image](https://user-images.githubusercontent.com/32943174/87479280-32ead200-c5f9-11ea-9de7-b318500d7426.png)

Link to the two comments in question:
1. https://ruqqus.com/post/171i/wut/3nmq
2. https://ruqqus.com/post/16yv/terrorist-attacks-per-ideology/3nmr?context=1

**Comment by drvladb** [comment]
There isn't a problem, its just different formatting between guilds, [see this](https://ruqqus.com/post/183u/test-re-httpsgithubcomruqqusruqqusissues327)
