### ISSUE TITLE
Embedded file/audio/video hosting?

### ISSUE THREAD

**Issue by shillshocked** [ruqqus/ruqqus#332]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Would be nice to have integration with a current service or a partnership with one

**Describe alternatives you've considered**
Catbox.moe comes to mind

**Additional context**
This allows content to be directly on the page and not relying on unknown third-parties.

**Comment by drvladb** [comment]
>  Would be nice to have integration with a current service or a partnership with one  
Like which service?  

> Describe alternatives you've considered  
Why not just use catbox  

> This allows content to be directly on the page  
It can just be embeded if its a video / audio  
Feel free to tag me if you have anything to tell me  

Other notes:
It costs quite a bit to run this, especially along with Ruqqus its self.
