### ISSUE TITLE
Created a Guild, server lagged, guild was created, but there is no guildmaster

### ISSUE THREAD

**Issue by shillshocked** [ruqqus/ruqqus#334]
https://ruqqus.com/+Idiocracy

**Comment by shillshocked** [comment]
Update on this. I've created two more since, then, same problem. It gives some kind of error 503 or 504 or something and then the guild is created, but there is no guildmaster. Bizarre...

**Comment by noahmaranesi** [comment]
Visit ruqqus.com/help/siege and you will be able to claim one per 30 days. That's something you can do while you wait for a response and fix.

**Comment by shillshocked** [comment]
Yeah well that makes three to siege so far...gonna take a while.
