### ISSUE TITLE
API should provide access to post comments as JSON

### ISSUE THREAD

**Issue by alesimula** [ruqqus/ruqqus#335]
It is not possible to access a post's comments without requesting the html page, https://ruqqus.com/api/v1/post/${pid} only returns a post without the comments;

It should be possible to access them, eg. via https://ruqqus.com/api/v1/post/${pid}/comments, which would expose get_post_with_comments

**Comment by drvladb** [comment]
This will be implemented with the adding of OAuth

**Comment by IThinkImOKAY** [comment]
It is now possible to get a submission's comment count by accessing the `comment_count` attribute. We can close this now.
