### ISSUE TITLE
JSON API should include the number of comments and upvotes

### ISSUE THREAD

**Issue by alesimula** [ruqqus/ruqqus#336]
The https://ruqqus.com/api/v1/post/${pid} url and feed API urls like https://ruqqus.com/api/v1/all/listing (and all the others) should include the number of comments and post score (upvotes-downvotes)

**Comment by mpieciak18** [comment]
Hey @alesimula - I worked on the solution for this.

I was going to commit the changes for my fork/branch, but wanted to test it out locally first. Unfortunately I'm on Ubuntu, so I had to use some Google-fu to adapt the local development/hosting directions in the readme.md file for my set up. I got everything to work except the import of the schema.txt into Postgresql.

Once I figure that out, I'll test out the changes, then commit them.

**Comment by IThinkImOKAY** [comment]
We can close this issue now.
