### ISSUE TITLE
I wanted to start contributing to this project, but schema.txt seems outdated

### ISSUE THREAD

**Issue by oicitrapdraz** [ruqqus/ruqqus#338]
1. Created `ruqqus` database and run `psql ruqqus -a -f schema.txt`
2. Tried to login/sign up, but it said patreon columns were missing, so I went to the model file, found what these columns were and then added them to the `schema.txt` file...
3. Deleted `ruqqus` database, created it and run `psql ruqqus -a -f schema.txt` again.
4. Now it says `comments.original_board_id` does not exist...

...

I don't have much experience with Flask, but considering how other web apps frameworks work where I do have a lot of experience (Rails, Django, etc.)  it doesn't seem right that you have to manually maintain `schema.txt` after each change, it's just not maintainable. Made a quick google search and [found this](https://flask-migrate.readthedocs.io/en/latest/), maybe you could use it or use another alternative.

**Comment by drvladb** [comment]
Hello, this is being worked on issue #321 and pull requests #328

**Comment by captainmeta4** [comment]
Make sure you are using a release package; schema.txt isn't always kept up to date since it's a "driven" file rather than a "driving" file.

**Comment by shillshocked** [comment]
Since the schema.txt isn't updated, is there a way to update it? Alternately, how do we update Ruqqus to the latest version after installing, because the .zip version isn't nearly as recent.

I'm in the same boat as the OP, I'd love to do some development but prefer the latest version.
