### ISSUE TITLE
No backup codes are generated when enabling two-factor authentication

### ISSUE THREAD

**Issue by noahmaranesi** [ruqqus/ruqqus#342]
I only just noticed now that Ruqqus does not generate any backup codes when you set up two-factor authentication. This was a huge oversight when implementing 2FA.

**Comment by noahmaranesi** [comment]
Bumping. This is a massive issue security wise.

**Comment by vulpinefoxxo** [comment]
bump

**Comment by noahmaranesi** [comment]
Closing. See: http://ruqqus.com/post/b5de
