### ISSUE TITLE
Posts and/or comments should display what Guild they originated from when being kicked and/or yanked from and to a Guild

### ISSUE THREAD

**Issue by noahmaranesi** [ruqqus/ruqqus#343]
Either:

1. Have a message informing the user at the top of the page regarding if this post has been on other Guilds.

    Example: "This post has also been on the following Guilds: +Guild1, +Guild2". This would be good for Guildmasters removing posts too (no need to write "This post was removed from +Guild1, please follow the rules").

2. Have all comments that originated from that Guild display a message – maybe next to where the username and title are shown – saying "This comment was from +Guild3".

**Comment by kek7198** [comment]
Currently, we display the origin guild if a post has been kicked to general. This is shown on the right sidebar (desktop).

**Comment by noahmaranesi** [comment]
However, let's say, I post something to +General, then someone yanks it and someone comments, I then remove my post from that Guild, there is no origin status/history.
