### ISSUE TITLE
Unsuccessful Guild Siege attempts should not trigger the cool-down period

### ISSUE THREAD

**Issue by noahmaranesi** [ruqqus/ruqqus#345]
I don't think this is a good idea. Any attempt - whether successful or - tiggers the cool-down period. Alternatively, if its unsuccessful, if there should be cool-down period, it should not be 30 days. 10 minutes, 1 hour or 24 hours are much more reasonable. 30 days is **maybe** fair for a successful siege. Or even having a rep requirement (if there is already, it's not described on the [help page](https://ruqqus.com/help/siege))

**Comment by kaijuagenda** [comment]
:thinking: i'd tend to agree, given that there still really isn't much of a way to 'tell' if someone's active or not. 

I know there's the "Active" flag shown in the guildmaster list, but I've done it in the past and that guildmaster was still "Active" the day of the successful siege.
