### ISSUE TITLE
Inconsistent app accent/theme color (Porpl)

### ISSUE THREAD

**Issue by SFM61319** [ruqqus/ruqqus#347]
This felt like a bug/inconsistency so I raised this issue.  
  
The [ruqqus icon](https://raw.githubusercontent.com/ruqqus/ruqqus/master/ruqqus/assets/images/logo/favicon.png "Favicon") and other porple icons have a color value of `#603abb` (a darker shade of porpl), while everywhere else in the app and website (like the buttons, the [ruqqus](https://ruqqus.com/) home page link, etc.) have a color value of `#805ad5`.  
  
@ruqqus, @captainmeta4, @kek7198 and @jakemayeux, which of them is the actual correct accent color (*Porpl*)? And will it be fixed or was it intentional?  
  
###### *I know this isn't THAT important but I'm trying to make a basic ruqqus UWP client (raised as a feature request in #295) which will of course have accent/porpl colored elements. Also, please help me with some icon-requests in #295 if possible, thank you!*

**Comment by kek7198** [comment]
#805AD5 is the correct color. I've pushed new images to master.

**Comment by SFM61319** [comment]
Hey, @kek7198, there is still some inconsistency in [the favicon](https://raw.githubusercontent.com/ruqqus/ruqqus/master/ruqqus/assets/images/logo/favicon.png). The icon's background color is `#8159d6`, while the color code for actual *Porple* is `#805ad5`. (I haven't checked all the other icons, but some of the others I checked are good).  
  
Also, can you tell me how you created these icons/modified them? I could use that software to make ruqqus icons of different dimensions asked for [here](https://github.com/ruqqus/ruqqus/issues/295#issuecomment-657275185).
