### ISSUE TITLE
Add Tooltip (Hover over) Text to GuildMaster's Avatar

### ISSUE THREAD

**Issue by ruledby** [ruqqus/ruqqus#352]
**Is your feature request related to a problem? Please describe.**
When looking at the avatar of a GM of a Guild, it isn't immediately known who it belongs to.  I have to look at where the avatar links to.

**Describe the solution you'd like**
Add a tooltip text displaying the profile name when you hover over the avatar. 

**Describe alternatives you've considered**
It might be cool to add a Facebook style hover-over event, where it shows the avatar, username, rep, and part of their bio, but that would be more complex. 

**Additional context**
![tooltip1](https://user-images.githubusercontent.com/3304201/88433899-da16f880-cdb3-11ea-9209-b4727b16c236.PNG)
![tooltip2](https://user-images.githubusercontent.com/3304201/88433912-e00cd980-cdb3-11ea-8620-5b1084d76f56.PNG)

**Comment by kek7198** [comment]
>It might be cool to add a Facebook style hover-over event, where it shows the avatar, username, rep, and part of their bio, but that would be more complex.

Popovers are something I'm working on the vue.js refactor :)

**Comment by ruledby** [comment]
> 
> 
> > It might be cool to add a Facebook style hover-over event, where it shows the avatar, username, rep, and part of their bio, but that would be more complex.
> 
> Popovers are something I'm working on with the vue.js refactor :)

That's cool.  I think it'd be nice if this repo had a roadmap.md to view, instead of trying to hunt it down on the dev's post history.  Kind of feel like I submitted this unnecessarily now haha.
