### ISSUE TITLE
Sort improvements

### ISSUE THREAD

**Issue by oicitrapdraz** [ruqqus/ruqqus#357]
**Describe what you'd like**

1. To be able to **save a default sorting**, e.g. "Hot" with time range "Day" in the profile settings, so that this setting is used by default in all views.

![image](https://user-images.githubusercontent.com/11054478/88490979-3709de80-cf6d-11ea-8f72-317f57914df5.png)

2. Also, I would like that when choosing a sort by, the request **to not** happen automatically, instead let me choose a time range **and** then make the request, why? Well, because after you choose a sort by option a request is automatically made, and if you want to choose another time range you have to wait for the entire request to be completed and then choose the desired time range.

![image](https://user-images.githubusercontent.com/11054478/88491003-79332000-cf6d-11ea-851c-df33b3dfb591.png)

**Comment by kek7198** [comment]
Good idea. This is probably something we could knock out in a twitch stream. @captainmeta4 thoughts?

**Comment by docyx** [comment]
@kek7198 could be done quite easily with `localStorage`.
