### ISSUE TITLE
Error(s) 404/500 with local development on Linux

### ISSUE THREAD

**Issue by mpieciak18** [ruqqus/ruqqus#378]
When following the instructions for local development on [README.md](https://github.com/ruqqus/ruqqus), the app itself should present no error messages (ie, 404 or 500) when being accessed or tested in a browser. 

The instructions for local development & deployment are specific for macOS, however.

In effort to adapt the instructions for Linux/Ubuntu, so I myself (and hopefully others) can start contributing to the project, I found a number of changes needed in the instructions. Along the way, I deployed the app and encountered an error 500 on all pages, found the workaround for that, and am now running into error 404 on all pages.

I've done the following:

Under "Install Dependencies", instead of using `brew install redis` and `brew install postgresql`, I used `sudo apt-get install redis` and `sudo apt-get install postgresql` to install Redis and PostgresQL.

Under "Start Services", instead of using `redis-server /usr/local/etc/redis.conf` and `brew services start postgresql`, I used `sudo service redis-server start` and `sudo service postgresql start` to start both Redis and PostgresQL. You can verify both services are running by entering in `sudo service redis-server status` and `sudo service postgresql status`. _Note: because Homebrew doesn't support `brew services` on Linux, this is ultimately why `sudo apt-get` and `sudo service`._

Additionally under "Start Services", instead of using `psql postgres -a -f schema.txt`, I used `sudo -u postgres psql -a -f schema.txt` to successfully restore the database dump.

Under "Add Test User to Database", instead of using `psql postgres` to access psql, I used `sudo -u postgres psql`.

Under "Refresh DNS", instead of using `sudo killall -HUP mDNSResponder`, I used `sudo systemd-resolve --flush-caches`.

_Up to this point, the app will deploy using the remaining directions under "Create Environment Variables" and "Run Ruqqus". However, each page will display an error 500._

`export DATABASE_URL=postgres://localhost:5432/postgres` is not appropriate on Linux, because by default, Linux expects connections to the database to be authenticated (ie, supplied with a password). When installing PostgresQL, a super user 'postgres' is created without specifying a password. To specify a password, first go into psql by entering `sudo -u postgres psql`. Then enter the following `ALTER USER postgres PASSWORD 'enter_password_here_without_quotes';`. Once that is done, you can set the environment variable for the database url as such: 
`export DATABASE_URL=postgresql://postgres:'your_password_without_quotes'@localhost:5432/postgres`

**After that, the error 500 issue when running Ruqqus is resolved, but now there's an error 404 on all the pages.**

**Comment by oicitrapdraz** [comment]
I think it would be better to have general instructions and maybe a couple of cases depending on the OS, because what's important to mention are stuff like what's the exact Python version, if redis must be running and on what port, if postgres must be running and on what port, what environment variable must be set, etc. Not all Linux commands are the same (e.g. Fedora vs. Debian) and about the Postgres authentication method, it depends. A lot of people work locally with `trust` connection type, in that case, you don't need to use a password, is it necessary to be explaining these things in the `README.md`? in my opinion, it's not but let's hear more opinions.
 
By the way, I would suggest moving these instructions out of the `README.md` and use Wiki entries only, because I believe such technical details make the `README.md` a bit messy.

**Comment by CrystalVulpine** [comment]
I got the same thing actually. When trying to submit a post it gave a 404, and trying to access the home page while logged in resulted in an internal server error (logged out was fine).

And adding the new commits I made yesterday caused an internal server error on nearly every page due to "UndefinedColumn" in postgres and it references a bunch of fields that aren't even in the code. I'm not great with SQL stuff so I have no idea how to fix it.

**Comment by mpieciak18** [comment]
> I think it would be better to have general instructions and maybe a couple of cases depending on the OS, because what's important to mention are stuff like what's the exact Python version, if redis must be running and on what port, if postgres must be running and on what port, what environment variable must be set, etc. Not even all Linux commands are the same (e.g. Fedora vs. Debian) and about the Postgres authentication method, it depends. A lot of people work locally with `trust` connection type, in that case, you don't need to use a password, is it necessary to be explaining these things in the `README.md`? I think it's not, but let's hear more opinions.
> 
> By the way, I would suggest moving these instructions out of the `README.md` and use Wiki entries only, because I find such technical details make the `README.md` a bit messy.

I agree 100% that there should general instructions and a few specific cases that are used as examples.

Adding all of that to the `README.md` would indeed make it messy. Perhaps having a separate installing instructions file would suffice?



> I got the same thing actually. I used #275 to run it on Ubuntu, and when trying to submit a post it gave a 404, and trying to access the home page while logged in resulted in an internal server error (logged out was fine).
> 
> And adding the new commits I made yesterday caused an internal server error on nearly every page due to "UndefinedColumn" in postgres and it references a bunch of fields that aren't even in the code. I'm not great with SQL stuff so I have no idea how to fix it.
> 
> What it comes down to is probably that Mac is a poor choice for an open-source project.

I have not tried setting up a Docker like mentioned in #275. However, I found that the 404 issue I was experiencing was 100% user error at this point. I did not pay attention to what the `domain` environment variable was being set as in the instructions, and was entering `localhost:8000` and not `ruqqus.localhost:8000` in my browser.

At this point, the local deployment works just fine, with the exception of the inability to successfully log in & remain logged in. I can log in using the dummy user, but upon successfully logging in, I am redirected to the homepage, logged out again.

**Comment by NotAGreyAlien** [comment]
> with the exception of the inability to successfully log in & remain logged in

I believe this is due to the use of secure cookies, whereas localhost is not run via https/ssl (see __main.py__, SESSION_COOKIE_SECURE). Looks like it can be set with an env var, so if you do an:

export SESSION_COOKIE_SECURE=false

As part of all those exports before running gunicorn, that might help with your login issue.

**Comment by mpieciak18** [comment]
@NotAGreyAlien Okay, I noticed this was an env var used in the Linux installation guide on the wiki, so I used that. However, I had updated my local fork to the master branch, and now I'm back to square one with 500 errors on every page.

**Comment by CrystalVulpine** [comment]
> @NotAGreyAlien Okay, I noticed this was an env var used in the Linux installation guide on the wiki, so I used that. However, I had updated my local fork to the master branch, and now I'm back to square one with 500 errors on every page.

That's not your fault, everyone is getting that right now. The schema appears to be outdated, which causes database errors.

**Comment by mpieciak18** [comment]
@NotAGreyAlien With the recommendation of one of the project owners, I rolled back my local installation to v2.15 and was able to test out your solution. It works and I'm able to log in & remain logged in.

@CrystalVulpine Rolling back to v2.15 fixes the issue for now, as the schema.txt is not kept up-to-date with every single commit.

**Comment by far-rainbow** [comment]
So how to fix it? 2.15 and further versions all give the same 404 as an answer
[Screenshot](http://prntscr.com/vyr7ou)
