### ISSUE TITLE
No favicon when Creating a Post or Guild

### ISSUE THREAD

**Issue by oicitrapdraz** [ruqqus/ruqqus#381]
## Expected Behavior
Show the favicon in every view.

## Current Behavior
![Screenshot from 2020-08-04 13-01-48](https://user-images.githubusercontent.com/11054478/89322830-d35d7080-d652-11ea-924d-995c34d2e607.png)
![Screenshot from 2020-08-04 12-59-19](https://user-images.githubusercontent.com/11054478/89322835-d5273400-d652-11ea-914c-bee0bd68c621.png)

**Comment by captainmeta4** [comment]
Fixing now
