### ISSUE TITLE
Linux install instructions are wrong

### ISSUE THREAD

**Issue by svpn** [ruqqus/ruqqus#387]
Following this guide:

https://github.com/ruqqus/ruqqus/wiki/Linux-Installation

In the **Initialize Database** section there is no Alembic installed, and it isn't present in requirements.txt

**Comment by MoogTheWizard** [comment]
>IN TESTING  
>Instructions are for testing the Alembic Integration  

Sounds like you want https://github.com/ruqqus/ruqqus/pull/328

**Comment by dginovker** [comment]
Big +1 for #328 getting merged. I've wanted to dev on Linux for months now but can never get it working.

**Comment by CrystalVulpine** [comment]
> Big +1 for #328 getting merged. I've wanted to dev on Linux for months now but can never get it working.

What issues are you having?

**Comment by dginovker** [comment]
> What issues are you having?

Every time I try it's a new issue.  Today I'm just getting "Internal Server Error": 
![image](https://user-images.githubusercontent.com/32943174/90342178-35fc2800-dfd4-11ea-8896-23314cd5c7cf.png)

**Comment by CrystalVulpine** [comment]
That's because schema.txt is outdated and which causes every page to fail with a 500 error due to poor database management. To avoid this, use tagged releases instead. The most recent one is here: https://github.com/ruqqus/ruqqus/releases/tag/2.15

**Comment by CrystalVulpine** [comment]
Tons of users got that problem, the docs should be updated to be more clear about this.

**Comment by shillshocked** [comment]
I would love to try this out but installing requirements.txt ended up with this after a while:

`ERROR: Command errored out with exit status 1: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-kuhnr3hk/gevent_b12056d55b5f442092e5377cb5acd2cc/setup.py'"'"'; __file__='"'"'/tmp/pip-install-kuhnr3hk/gevent_b12056d55b5f442092e5377cb5acd2cc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-chsrlepe/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.9/gevent Check the logs for full command output.`

I'm using Arch Linux.

**Comment by kek7198** [comment]
Linux installation guide has been updated and fixed.
