### ISSUE TITLE
column submissions.upvotes does not exist

### ISSUE THREAD

**Issue by jaspreetsinghrawel** [ruqqus/ruqqus#390]
Hello All,

I am facing the below error while trying to run "gunicorn ruqqus.__main__:app -w 3 -k gevent --worker-connections 6 --preload --max-requests 500 --max-requests-jitter 50"

**sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column submissions.upvotes does not exist**

### My Environment -

Ubuntu 18.04
python3.6
Took a clone of code of master branch

### Steps Followed -

sudo pip3 install -r requirements.txt
sudo apt-get install redis
sudo apt-get install postgresql
sudo service redis-server start
sudo service postgresql start
sudo -u postgres psql -a -f schema.txt
sudo -u postgres psql
INSERT INTO users (id, username, email, passhash, created_utc, creation_ip, tos_agreed_utc, login_nonce) VALUES (NEXTVAL('users_id_seq'), 'ruqqie', 'ruqqie@ruqqus.com', 'pbkdf2:sha512:150000$vmPzuBFj$24cde8a6305b7c528b0428b1e87f256c65741bb035b4356549c13e745cc0581701431d5a2297d98501fcf20367791b4334dcd19cf063a6e60195abe8214f91e8', 1592672337, '127.0.0.1', 1592672337, 1);
Add this line to /etc/hosts --> 127.0.0.1 ruqqus.localhost
sudo systemd-resolve --flush-caches
sudo -u postgres psql postgres
\password postgres  --> set the password as postgres
\q
In /etc/postgresql/12/main/pg_hba.conf, change peer to md5 for local sockets
export domain=ruqqus.localhost:8000
export REDIS_URL=redis://localhost:6379
export DATABASE_URL=postgres://postgres:postgres@localhost:5432/postgres
export PYTHONPATH=/home/jaspreet/ruqqus
export MASTER_KEY=$(openssl rand -base64 32)
gunicorn ruqqus.__main__:app -w 3 -k gevent --worker-connections 6 --preload --max-requests 500 --max-requests-jitter 50

**Comment by oicitrapdraz** [comment]
Sadly in this project it has always been a pain in the ass the fact that `schema.txt` is not always updated.

Let's hope that this problem will be solved sometime since it hinders a lot the contributions that many developers want to make.

**Comment by mpieciak18** [comment]
@jaspreetsinghrawel My local installation has been plagued by this, too.
