### ISSUE TITLE
Remove New Relic

### ISSUE THREAD

**Issue by comradekingu** [ruqqus/ruqqus#391]
Why not instead use self-hosted [Matomo](https://en.wikipedia.org/wiki/Matomo_(software)), or a similar alternative?

**Comment by danbeneventano** [comment]
New Relic is focused on tracking site performance while Matomo is user analytics

**Comment by comradekingu** [comment]
@danbeneventano Whatever the focus, the leaking of data to their servers is the problem to solve.
Any solution (including just not using it) is fine by me.

**Comment by captainmeta4** [comment]
Newrelic is anonymized client- and server-side performance analytics.
