### ISSUE TITLE
Internal Server error when unlinking patreon

### ISSUE THREAD

**Issue by animeking9901** [ruqqus/ruqqus#395]
Issue tracker is **ONLY** used for reporting bugs.

## Expected Behavior
Unlink patreon

## Current Behavior
Internal Server error,patreon still linked

## Possible Solution
Make unlinks successful,my(now deleted) account LoliConsumer is still linked preventing me from moving to my much better username

## Steps to Reproduce(Desktop)
1. Click username
2. click settings
3. Scroll to Linked Accounts
4. Attempt to unlink patreon

## Context (Environment)
Made a account with a better username, and cannot move my patronage over due to the unlink failing even after account deletion

**Comment by captainmeta4** [comment]
Just fixed
