### ISSUE TITLE
A button to block guilds directly from all

### ISSUE THREAD

**Issue by PhantomDerp** [ruqqus/ruqqus#407]
It's kind of annoying having to click to my profile whenever I find a new furry guild in all I need to block.

It would be nice to have a button that blocks the guild a post is in.

It could be next to the flag button and look something like this:

![image](https://user-images.githubusercontent.com/42085302/90244256-65f1d280-ddfe-11ea-8c39-f3ca245794a4.png)

**Comment by kek7198** [comment]
Done 👍

**Comment by PhantomDerp** [comment]
![image](https://user-images.githubusercontent.com/42085302/90573484-8b773700-e184-11ea-8b4d-20c3397ab65c.png)
