### ISSUE TITLE
Marking as political and sorting for apolitical (Guild tagging)

### ISSUE THREAD

**Issue by PhantomDerp** [ruqqus/ruqqus#408]
A simple political mark similar to the nsfw and nsfl marks and a way to sort to avoid it

Could look like this 
![ruq](https://user-images.githubusercontent.com/42085302/90245167-26c48100-de00-11ea-9f5b-2b45e4899164.png)

**Comment by oicitrapdraz** [comment]
Although it's a good idea, it's difficult to implement. As someone already mentioned I think the best way would be to implement a Guild tagging system (news, country, history, politics, music, etc.), so the users could filter by tags.

**Comment by PhantomDerp** [comment]
Changed the title to mention guild tagging

**Comment by Nakilon** [comment]
I don't think there should be global tags. They'll be used to manipulate. If you don't want people to know something you tag it with some "boring" word, such as "political" and say "booooo it's poliiiiitical, gtfooooo".
If you want to tag the guilds you aren't yet filtered out from the All I suppose you want to give them own tags. Similar to putting to a private multireddit.
