### ISSUE TITLE
How to set sqlalchemy.url？

### ISSUE THREAD

**Issue by Orca-web** [ruqqus/ruqqus#410]
**Edit alembic.ini and verify sqlalchemy.url points to the correct database.**

I have a problem at this step.

1.  `sqlalchemy.url = postgres://postgres:postgres@2019@localhost:5432/postgres `
    or `sqlalchemy.url = postgresql://postgres:postgres@2019@localhost:5432/postgres`

Error warning：

`sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  Ident authentication failed for user "postgres"`

![image](https://user-images.githubusercontent.com/59247295/90267396-10620800-de88-11ea-973d-79270f388a90.png)

2. sqlalchemy.url = driver://postgres:postgres@2019@localhost:5432/postgres

Error warning：

`sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:driver`

![image](https://user-images.githubusercontent.com/59247295/90267900-c62d5680-de88-11ea-9445-a5a4bf382326.png)

Who could tell me how to set sqlalchemy.url？for examples? （Use PostgreSQL database）

**Comment by init-i** [comment]
The url format is postgres://USERNAME:PASSWORD@HOST:PORT

It's failing authentication meaning your username and password don't match up. To set the password, run:

    $ sudo -iu postgres

Then from the postgres user, run
 
    $ psql

Then run

    \password

and set the password. You can set it to "postgres" to keep the database_url the same. If you set it to something else, make sure to change the database URL accordingly.

**Comment by Orca-web** [comment]
@init-i  

**Follow your suggestions and the problem still cannot be solved.**

### My operation process record

1.  set the password
```
sudo -iu postgres
psql
\password
Enter new password: postgres
Enter it again: postgres
```
![image](https://user-images.githubusercontent.com/59247295/90274202-c03c7300-de92-11ea-9411-0dfbf836211c.png)


2. `sqlalchemy.url = postgres://postgres:postgres@localhost:5432/postgres`

![image](https://user-images.githubusercontent.com/59247295/90274663-8a4bbe80-de93-11ea-9d9c-fca3f3af7449.png)

because I running the app on VPS(IP:47***4)

`sqlalchemy.url = postgres://postgres:postgres@47****4:5432/postgres`

**Error : could not connect to server: Connection timed out**

**my port:**
![image](https://user-images.githubusercontent.com/59247295/90275128-6177f900-de94-11ea-8a8e-80d4fd924597.png)

![image](https://user-images.githubusercontent.com/59247295/90275649-3510ac80-de95-11ea-9fec-b8a98126777e.png)

**Comment by Korkd** [comment]
It's likely failing when connecting to the IP because you don't have the [pg_hba.conf](https://www.postgresql.org/docs/12/auth-pg-hba-conf.html) configured for it.

Are you able to connect to postgres via `psql --u postgres`?

**Comment by Orca-web** [comment]
@Korkd

> Are you able to connect to postgres via psql --u postgres?

I able to connect to postgres via `psql --u postgres`

![image](https://user-images.githubusercontent.com/59247295/90300317-86885e00-decc-11ea-9782-7ed1fe0e5001.png)

> Did you configure the pg_hba.conf for localhost?  and what the listen_addresses is in the postgresql.conf file？

Before, I kept these file default settings.Following your suggestion, I reconfigure them.

The following code is my configuration

**pg_hba.conf**

```
# Put your actual configuration here
# ----------------------------------
# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     trust

# IPv4 local connections:
host    all             all             127.0.0.1/32            trust
host    all             all             47.97.254.160:24        trust

# IPv6 local connections:
host    all             all             ::1/128                 ident

# Allow any user from any host with IP address 192.168.93.x to connect
# to database "postgres" as the same user name that ident reports for
# the connection (typically the operating system user name).
host    postgres        all             47.97.254.160/24         ident

# Allow any user from host 192.168.12.10 to connect to database
# "postgres" if the user's password is correctly supplied.
host    postgres        all             47.97.254.160/32        scram-sha-256

# Allow replication connections from localhost, by a user with the
# replication privilege.
local   replication     all                                     peer
host    replication     all             127.0.0.1/32            ident
host    replication     all             ::1/128                 ident
```

**postgresql.conf**

`listen_addresses = '*'	or  listen_addresses = '47.97.254.160'`



the same error : could not connect to server: Connection timed out

![image](https://user-images.githubusercontent.com/59247295/90300891-3bbc1580-decf-11ea-9422-596d3da304e2.png)


Since I am not very good at these operations, please review them.

**Comment by Korkd** [comment]
Well first off, never use `trust` on anything but localhost. It means that can connect without any password, regardless of it one is set.

You also have a typo in `47.97.254.160:24` which might be causing problems.

Here's what I'd recommend for troubleshooting:

```
# Put your actual configuration here
# ----------------------------------
# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     trust

# IPv4 local connections:
host    all             all             127.0.0.1/32            password

# IPv6 local connections:
#host    all             all             ::1/128                 ident

# Allow any user from any host with IP address 192.168.93.x to connect
# to database "postgres" as the same user name that ident reports for
# the connection (typically the operating system user name).
host    postgres        all             47.97.254.160/32         password

# Allow any user from host 192.168.12.10 to connect to database
# "postgres" if the user's password is correctly supplied.
#host    postgres        all             47.97.254.160/32        scram-sha-256

# Allow replication connections from localhost, by a user with the
# replication privilege.
local   replication     all                                     peer
host    replication     all             127.0.0.1/32            ident
host    replication     all             ::1/128                 ident
```

This lets you connect over the local socket without any password. Any connection over and IP will require a password (plain text). You will likely want to use md5 or scram-sha-256 once you get it working for security reasons.

keep it `listen_addresses = '*'`

**Comment by Orca-web** [comment]
@Korkd and @init-i  Thanks for taking the time to contribute an answer.

@Korkd Your suggestion is great. I solved the problem according to your answer.

I reconfigure pg_hba.conf

```
# TYPE  DATABASE        USER            ADDRESS                 METHOD
# "local" is for Unix domain socket connections only
local   all             all                                     md5
# IPv4 local connections:
host    all             all             127.0.0.1/32            md5
# IPv6 local connections:
host    all             all             ::1/128                 md5
# Allow replication connections from localhost, by a user with the
# replication privilege.
local   replication     all                                     peer
host    replication     all             127.0.0.1/32            ident
host    replication     all             ::1/128                 ident
```
then

`(myenv) [root@iZbp18spopcy0h6gof6twfZ ruqqus]# alembic upgrade head`


**Run successfully**

![image](https://user-images.githubusercontent.com/59247295/90302879-eb978000-dedb-11ea-8b53-2374e4b38653.png)

**Comment by Korkd** [comment]
Are you sure that machine has that IP bound to it? Would need to look at what all the interfaces are bound to.

**Comment by Orca-web** [comment]
> Are you sure that machine has that IP bound to it?

I installed ruqqus on my vps, not on my local computer.
My Xshell has been successfully connected to VPS. so I am sure I know this IP is correct

> Would need to look at what all the interfaces are bound to.

I don't know how to look at what all the interfaces are bound to.
