### ISSUE TITLE
Can't register, get a 403 forbidden.

### ISSUE THREAD

**Issue by sergiotapia** [ruqqus/ruqqus#412]
![image](https://user-images.githubusercontent.com/686715/90317843-31fbd780-defa-11ea-91a0-87eae7f424bc.png)

Trying to register an account and try out the platform but I get this above every time. Tried on different machines and even mobile. 

Appreciate the help!

**Comment by kek7198** [comment]
Should be fixed now

**Comment by sergiotapia** [comment]
Can you confirm it works now, thank you
