### ISSUE TITLE
Migrate antiquated HTML templating for frontend to a fetch api

### ISSUE THREAD

**Issue by DGKSK8LIFE** [ruqqus/ruqqus#414]
**Is your feature request related to a problem? Please describe.**
HTML templating injection is antiquated and hard to scale. Also makes implementing a mobile platform for the app much harder

**Describe the solution you'd like**
Serve a REST/GraphQL api on the backend which any client could request (you could rewrite the frontend in React, too!)

**Describe alternatives you've considered**
None

**Comment by kek7198** [comment]
We are refactoring in vue.js, using Apollo for GraphQL.

**Comment by DGKSK8LIFE** [comment]
@kek7198 how can I help. I'd love to support the cause.
