### ISSUE TITLE
Can't link to HTTP-only URLs in comments

### ISSUE THREAD

**Issue by thparkth** [ruqqus/ruqqus#416]
Issue tracker is **ONLY** used for reporting bugs.

## Expected Behavior
When I use the []() syntax to include a link to an http URL in a comment, I expect the resulting link to use the HTTP URL scheme, not HTTPS, so that users can successfully follow a link to a site which does not support HTTPS.

## Current Behavior
When the comment is displayed, the URL is rewritten with an HTTPS URL scheme. For sites which do not support HTTPS this results in an error.

## Possible Solution
I note that if I edit the comment, the original non-secure HTTP URL is still present.

## Steps to Reproduce
Live example: https://ruqqus.com/post/2cdo/challenge-tell-us-why-your-favorite/7va7

## Context (Environment)
The future of the web will be HTTPS only, and it is good to encourage that, but if this is deliberate behavior I suggest it is unhelpful. Perhaps it would be better to flag the "insecure link" or other similar non-breaking behavior.

**Comment by thparkth** [comment]
From the [code](https://github.com/ruqqus/ruqqus/blob/1efc28e1ab57cff48d9a36ff85e97445b78d577d/ruqqus/helpers/sanitize.py#L58) it appears that this is a deliberate decision.

I suggest that it is a bad decision. If the intention is to feed back to sites that they should support https, this isn't realistically going to help with that, but it does break functionality.

**Comment by CrystalVulpine** [comment]
The admins have indeed stated that this is intended. They're concerned about security and privacy, and the last thing they want is for a user to click on an insecure link. Almost every site supports https now so it's not a huge issue, users will just have to copy & paste http links if they're positive they want to access them.

**Comment by captainmeta4** [comment]
Forcing HTTPS is a deliberate decision to protect the safety, security, and privacy of users.
