### ISSUE TITLE
SSL Error when visiting ruqqus.com. 

### ISSUE THREAD

**Issue by AgeOfMarcus** [ruqqus/ruqqus#420]
Issue tracker is **ONLY** used for reporting bugs.

## Expected Behavior

Ruqqus should load fine
## Current Behavior

SSL Error: 
![image](https://user-images.githubusercontent.com/27669378/90652377-020b4780-e20c-11ea-9b50-0769351d8292.png)

## Possible Solution

Update certificate
## Steps to Reproduce

1. visit https://ruqqus.com. in your browser
2.
3.
4.

**Comment by OMGYourPasswordPolicysucks** [comment]
Looking at the vendor it seems they face the same issue. I wager this may something that may be fixable with a cloudflare rule.

https://heroku.com./
