### ISSUE TITLE
API's guild listing endpoint requires an auth token to be sent, but it shouldn't

### ISSUE THREAD

**Issue by maciejpedzich** [ruqqus/ruqqus#431]
## Summary
Upon sending a request to `https://ruqqus.com/api/v1/guild/<guildname>/listing`, you get a "Bad Request" error, due to a missing auth token.

## Expected Behavior
 You should get a JSON response as an array of posts, which belong to a guild with name equal to specified `<guildname>` parameter.

## Current Behavior
Instead, you get a `400 Bad Request. Authorization token not provided` error. It's weird, because all the other endpoints don't require any auth token to be sent at all.

## Steps to Reproduce
1. Just send a `GET` request to, for instance, `https://ruqqus.com/api/v1/guild/DankMemes/listing`

## Context (Environment)
I'm working on an unofficial Node.js wrapper for Ruqqus API, and as I mentioned earlier, it's weird that you get this error, while other endpoints work just fine without sending an auth token.

**Comment by DGKSK8LIFE** [comment]
@maciejpedzich This could be a potential vulnerability; seems like the developers' desire was to authenticate for each 3rd party api route. If not, then there should be no authentication for any of the routes.

**Comment by oicitrapdraz** [comment]
@DGKSK8LIFE At least Reddit doesn't need authentication, look at this example: [https://www.reddit.com/r/ruqqus.json](https://www.reddit.com/r/ruqqus.json)

I understand the need to create an app if I'm going to comment or post content, but just to find out how many subscribers a Guild has?

**Comment by DGKSK8LIFE** [comment]
@oicitrapdraz Well atm, to gain access to the ruqqus oauth api, you need to have a token (which is approve individually and given by the ruqqus dev team). The api will soon allow update, create, and delete access; which is why we need to authenticate our api clients properly. If it were read only, then no problem, but that's not how it's going to stay.
