### ISSUE TITLE
Deleted comments show up on admin userpages

### ISSUE THREAD

**Issue by CrystalVulpine** [ruqqus/ruqqus#432]
## Expected Behavior

As for most users, deleted comments shouldn't be listed on the profile page of an admin.

## Current Behavior

It shows the "[Deleted by author]" comment in the profile listing.

![](https://i.imgur.com/m5HQhBD.png)

## Possible Implementation

I don't know how this is happening. I looked in `user.commentlisting` but it looks like it already filters out deleted comments. Perhaps `v` is for somehow getting mixed up with the author of the comment instead of the logged in user, though I doubt that.

**Comment by captainmeta4** [comment]
This is wierd as shit.

The relevant code is:

```
        if not (v and (v.admin_level >=3)):
            comments=comments.filter_by(is_deleted=False)
```

classes/users.py line 287

Logged out user: `v and (anything)` evaluates to False. `not False` -> `True` -> filter by deleted.

And yet, logged out, I see "deleted by author" entries for my own deleted comments.

**Comment by CrystalVulpine** [comment]
Maybe it's written wrong or something. I don't know much about python but js is weird that way and writing something the wrong way can cause incorrect parsing. Maybe try `if not v or v.admin_level < 3:` instead.

**Comment by arkit3kt** [comment]
resolved
https://github.com/ruqqus/ruqqus/commit/c6496842a03ff4e5a43cdaf3ed82d78b0bbf8445

**Comment by CrystalVulpine** [comment]
@arkit3kt Are you sure about this? I'm pretty sure I saw a deleted comment on profiles a few times recently, but the commit you referenced was made 29 days ago, the same day I opened this issue.
