### ISSUE TITLE
Random post button returns "500 Internal server error"

### ISSUE THREAD

**Issue by Panjkrc** [ruqqus/ruqqus#435]
Issue tracker is **ONLY** used for reporting bugs.

## Expected Behavior
Button should redirect to random post

## Current Behavior
When you press random post button it shows "500 Internal server error"

## Steps to Reproduce

 When on desktop press first button to the left of your profile image, after that press "post" button

Direct link to the random post: https://ruqqus.com/random/post

**Comment by DGKSK8LIFE** [comment]
I think this is instigated by server downtime for deploy ask @captainmeta4 about this. (mentioned in #436 )

**Comment by captainmeta4** [comment]
Fixed
