### ISSUE TITLE
Mobile: requesting desktop site does not work

### ISSUE THREAD

**Issue by Foxite** [ruqqus/ruqqus#440]
I'm using Firefox for Android, and when I try to request the desktop version of a page, I still see the mobile version, only with larger viewport. This makes it impossible to view the sidebar, which is currently the only place where it tells you if a post has been kicked (#343).

**Comment by captainmeta4** [comment]
Currently behaving more or less as intended, since mobile vs desktop is based purely view width (on desktop, shrink the window width - you'll eventually get mobile layout without a refresh)
