### ISSUE TITLE
Friending System

### ISSUE THREAD

**Issue by ImOsaym** [ruqqus/ruqqus#441]
**Is your feature request related to a problem? Please describe.**
Not really.

**Describe the solution you'd like**
I think that when the DM system is rolled out, there should be some sort of friend system implemented. It would be different from a "follow" and you would have a friend's list as well. (Similar to https://ruqqus.com/mine?kind=users)

**Describe alternatives you've considered**
Maybe if 2 people follow each other, it would create a "friend?" Or when you create a DM, a prompt to send friend request would pop up?

**Additional context**
Adding a friending system would help Ruqqus spread more by the means of word by mouth.
EX: Bro add me on Ruqqus and we can talk!

**Comment by DGKSK8LIFE** [comment]
I agree with implementing this functionality. But I'd like it to be less "in your face" than what you described.

**Comment by kek7198** [comment]
Something I'd like to explore after vue and DMs are rolled out

**Comment by OzZVidz** [comment]
yay! Okay!

**Comment by kek7198** [comment]
We can explore this after Vue. For now, we have introduced bells with #678 which allows you to receive notifications when people post. Closing for now.
