### ISSUE TITLE
Invalid redirect_uri...

### ISSUE THREAD

**Issue by oicitrapdraz** [ruqqus/ruqqus#444]
I'm trying to [do step 2 in your tutorial](https://ruqqus.com/help/oauth), but I'm getting `{"oauth_error":"Invalid redirect_uri"}`, why does this happen? I'm using the same URI ([https://ruqqus-metrics.com](https://ruqqus-metrics.com)) in my API app settings.

## Expected Behavior
To show the view where I can authorize my app.

## Current Behavior
`Shows an error`

**Comment by DGKSK8LIFE** [comment]
could you test it in postman and then show the entire response? Thanks @oicitrapdraz

**Comment by DGKSK8LIFE** [comment]
I think this may be a problem with your code/not adding a valid redirect URI. What redirect URI did you pass? I haven't integrated much with the oauth api but I helped write the python library for it so I think I can help.

**Comment by oicitrapdraz** [comment]
> could you test it in postman and then show the entire response? Thanks @oicitrapdraz

Postman? How? It's supposed to be done in the browser, the instruction is: `Send your user to https://ruqqus.com/oauth/authorize, with the following URL parameters:`

> I think this may be a problem with your code/not adding a valid redirect URI. What redirect URI did you pass? I haven't integrated much with the oauth api but I helped write the python library for it so I think I can help.

`https://ruqqus-metrics.com/`

**Comment by DGKSK8LIFE** [comment]
you can run postman on any URL in the web @oicitrapdraz. Is the redirect URL an optional arg? I'm not entirely sure what it does. This is more of a captainmeta question tbh.

**Comment by oicitrapdraz** [comment]
> you can run postman on any URL in the web @oicitrapdraz

Well, if I do it in postman it ask me to log in lol.

![Screenshot from 2020-09-02 11-07-59](https://user-images.githubusercontent.com/11054478/92001418-a7461580-ed0c-11ea-81ea-39a2e4e08a2c.png)

**Comment by DGKSK8LIFE** [comment]
ok; so it seems like authentication works then.

**Comment by oicitrapdraz** [comment]
Oauth authentication? It's not working well for me.

**Comment by DGKSK8LIFE** [comment]
Hmm. Why did you close the issue? @oicitrapdraz

**Comment by oicitrapdraz** [comment]
> Hmm. Why did you close the issue? @oicitrapdraz

From one attempt to the other it started to work, but I don't know why.

**Comment by DGKSK8LIFE** [comment]
k
