### ISSUE TITLE
Oauth 404 Page Not Found?

### ISSUE THREAD

**Issue by oicitrapdraz** [ruqqus/ruqqus#446]
I was using [https://ruqqus.com/oauth/grant?grant_type=code](https://ruqqus.com/oauth/grant?grant_type=code) just fine a couple of hours ago, but I started to get 404 Page Not Found since 2~3 hours ago.

**Comment by DGKSK8LIFE** [comment]
@oicitrapdraz There have been recent deploys of ruqqus; check to see if routes have changed. @captainmeta4 Have query strings changed for the oauth api?
