### ISSUE TITLE
Comment replies are broken

### ISSUE THREAD

**Issue by CrystalVulpine** [ruqqus/ruqqus#452]
I just posted two comments, and it said they were submitted successfully. However when I reloaded the page, they did not appear in the thread, and the comment count did not go up. The two comments also do not appear in my comment history. It appears that new comments are no longer being saved to the database for some reason.

Edit: Okay this is weird af. I posted a test comment to another thread and it worked: https://ruqqus.com/post/2y2l/ruqqus-dev-stream--7pm-eastern/a8gy

~~It appears to only affect one particular thread.~~ And if I click on the permalink to a comment I can see my hidden replies: https://ruqqus.com/post/2y0v/massive-mental-block/a7ub

https://ruqqus.com/post/2y0v/massive-mental-block/a7s5

But they don't count in the comment count, and are not visible in the main thread or my profile page: https://ruqqus.com/post/2y0v/massive-mental-block

https://ruqqus.com/@CrystalVulpine/comments

Also, strangely clicking "permalink" on these comments just reloads the current page. They do not have a permalink at all (`href=""`). I found this out when clicking the permalink in my inbox and being led to the same inbox page instead of the comment. These comments also cannot be edited.

Edit 2: I got a notification in my inbox which I assume was a reply to a comment I made. Due to it being broken, my inbox now shows a 500 Internal Server Error.

I can also now confirm that this is affecting *all* threads, not just that one I mentioned. I originally thought it was only the one thread but that was because my first test comment in the other thread was a top-level one. I tried making a reply there and it also didn't work.

**Comment by DGKSK8LIFE** [comment]
Maybe this is due to latency/hosting service architecture? This might be a frontend bug too

**Comment by CrystalVulpine** [comment]
This appears to have been fixed.
