### ISSUE TITLE
Created account did the catcha, redirected me to cloudflare, then it asks me to create an account again

### ISSUE THREAD

**Issue by DGKSK8LIFE** [ruqqus/ruqqus#454]
Issue tracker is **ONLY** used for reporting bugs.

## Expected Behavior
Account should've been created and ruqqus should've authenticated me/logged me in. 

## Current Behavior

I was redirected to cloudflare to do another captcha set then I was redirected to the signup page again.

## Possible Solution
Unsure. Maybe removing some redirects/changing authentication scheme with captchas?

## Steps to Reproduce

Unsure if one just can.

## Context (Environment)

Trying to sign up for ruqqus

**Comment by DGKSK8LIFE** [comment]
Perhaps this is instigated by me failing to do the captcha properly?

**Comment by ForeverZer0** [comment]
Can confirm, this has happened twice to me while created bot accounts for API testing.

**Comment by DGKSK8LIFE** [comment]
@captainmeta4 Will probably get on it after he successfully deploys to AWS.

**Comment by captainmeta4** [comment]
Should be fixed now
