### ISSUE TITLE
implement functionality that allows you to make your own color theme on ruqqus

### ISSUE THREAD

**Issue by DGKSK8LIFE** [ruqqus/ruqqus#456]

**Comment by CrystalVulpine** [comment]
Do you mean for guilds? I could try to make a pr for this. Apparently it already works if you use inspect element, so all that's needed is a box to type in the color code.

**Comment by DGKSK8LIFE** [comment]
no color theme just on the client side for the entire app @CrystalVulpine

**Comment by DGKSK8LIFE** [comment]
Inspect element is less user friendly and doesn't persist/inspect element color theme isn't stored in the app's state (so if you close the ruqqus tab it won't persist/sustain the color changes you've made)

**Comment by CrystalVulpine** [comment]
I know, I meant the functionality already exists and inspect element *proves* that, it just hasn't been added yet.

**Comment by DGKSK8LIFE** [comment]
what i meant was functionality _within the app_; not functionality in the browser lol

**Comment by Samplasion** [comment]
Correct me if I'm mistaken, he's basiclly saying, make a page in the user settings that lets you select an accent color other than Ruqqus' purple _for you in your client_ that can be overridden by guild specific settings

**Comment by captainmeta4** [comment]
Done

**Comment by captainmeta4** [comment]
#457
