### ISSUE TITLE
Additional issues with the AWS migration

### ISSUE THREAD

**Issue by CrystalVulpine** [ruqqus/ruqqus#459]
I'll list them here as I find more. Please submit any others you find too.

---

* Recent posts lost all or some of their upvotes (even the author's initial vote is gone).
* ~~Dark mode only works on some pages now.~~ FIXED
* Rep and votes on posts up to 10 days ago continues to disappear. I lost 200 rep after the initial migration, 200 more a few hours later, and 30-40 more a few hours after that. Some posts that had previously retained some or all of their votes have now also lost them.

**Comment by DGKSK8LIFE** [comment]
@CrystalVulpine I have experienced the latter problem too: 
![image](https://user-images.githubusercontent.com/45473363/92316559-7c351d80-efbb-11ea-8c9a-aa29945669ae.png)
