### ISSUE TITLE
Adding a comment to my own post removes one upvote

### ISSUE THREAD

**Issue by carlosdangerslaptop** [ruqqus/ruqqus#46]
Adding a comment to my own post removes one upvote

Steps to reproduce:
1. I post a link, I then have 1 upvote
2. I comment on my own post, I then have 0 upvotes.

If this is defined because you shouldn't comment on your own posts, so be it. But I've been doing that for like a decade.

**Comment by carlosdangerslaptop** [comment]
@kek7198 @captainmeta4

**Comment by captainmeta4** [comment]
Vote count is fuzzed. A post/comment with 1 total upvote may display 0, 1, or 2 for its score.
