### ISSUE TITLE
Giphy Search does not work 

### ISSUE THREAD

**Issue by DGKSK8LIFE** [ruqqus/ruqqus#461]
Issue tracker is **ONLY** used for reporting bugs.

## Expected Behavior
When I type input in the input box, and press enter, I should get search results.

## Current Behavior
No search results:
![image](https://user-images.githubusercontent.com/45473363/92328896-91489580-f029-11ea-8ccd-61b6484058c6.png)

**Comment by ozgurerturk** [comment]
![giphy_notworking](https://user-images.githubusercontent.com/44666688/92509455-f4495080-f212-11ea-87b7-4e54057dbbdc.PNG)
another picture

**Comment by captainmeta4** [comment]
fixed now
