### ISSUE TITLE
Cloudflare returning 502 on attempted site visit 

### ISSUE THREAD

**Issue by DGKSK8LIFE** [ruqqus/ruqqus#463]
![image](https://user-images.githubusercontent.com/45473363/92347748-aad3f680-f096-11ea-9ee3-578023386d11.png)

**Comment by DGKSK8LIFE** [comment]
It's back up; but a lot of shit like this is happening intermittently so keep an eye out for anything out of the ordinary @captainmeta4

**Comment by lithiumjs** [comment]
It flops every once in a while.

**Comment by DGKSK8LIFE** [comment]
Yeah i

**Comment by DGKSK8LIFE** [comment]
I think it depends on where you are in the U.S./in relation to cloudflare's serves

**Comment by captainmeta4** [comment]
Server restart to install newrelic.

**Comment by DGKSK8LIFE** [comment]
k ty @captainmeta4
