### ISSUE TITLE
Enable an API endpoint to get all the Guilds

### ISSUE THREAD

**Issue by oicitrapdraz** [ruqqus/ruqqus#469]
**Is your feature request related to a problem? Please describe.**
I'm the developer of [https://ruqqus-metrics.com](https://ruqqus-metrics.com) and I don't want to have to scrape Ruqqus to get the name of the Guilds, plus the NSFW Guilds don't appear.

**Describe the solution you'd like**
An `/api/v1/guilds` endpoint so I can get a JSON response (paginated obviously), something like `[ { name: 'blah blah', ... }, { name: 'jojo jojo', ... }, ... ]`

**Comment by captainmeta4** [comment]
/api/v1/guilds
