### ISSUE TITLE
"undefined" error when trying to Subscribe to an account on private mode.

### ISSUE THREAD

**Issue by EP1CxEMAN08** [ruqqus/ruqqus#472]
I wanted to see if Subscribing to an account on private mode would do anything. However, when I pressed the button to Subscribe, it pops up a message saying "undefined." I would expect it to say something like "You can't subscribe to this user because they're on private mode," or something like that.

**Comment by CrystalVulpine** [comment]
I also noticed that some private users still have subscribers, and *sometimes* I actually am able to follow private users, but other times I get the undefined error.

**Comment by PauloBoks** [comment]
I just followed to someone, refreshed, their subscribers went up by one but the button for "subscribe" didn't change and now i get the "undefined" error.

Maybe the admins can check if I (@PauloBoks) follow @IsaiahIsacc765 to see if it worked or not

**Comment by PauloBoks** [comment]
I also get an error on the devtools console.

Hitting "copy message" gave me this:

XHRPOSThttps://ruqqus.com/api/follow/IsaiahIsacc765
[HTTP/2 409 Conflict 860ms]

	
POST
	https://ruqqus.com/api/follow/IsaiahIsacc765
Status409
Conflict
VersionHTTP/2
Transferred46.63 KB (45.30 KB size)

    	
    access-control-allow-headers
    	Origin, X-Requested-With, Content-Type, Accept, x-auth
    access-control-allow-origin
    	ruqqus.com
    alt-svc
    	h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400
    cache-control
    	private
    cache-control
    	maxage=600
    cf-cache-status
    	DYNAMIC
    cf-ray
    	5d1e67084b11f75c-GRU
    cf-request-id
    	0526deb92e0000f75c979d6200000001
    content-type
    	text/html; charset=utf-8
    date
    	Sun, 13 Sep 2020 02:22:47 GMT
    expect-ct
    	max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
    feature-policy
    	geolocation 'none'; midi 'none'; notifications 'none'; push 'none'; sync-xhr 'none'; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; speaker 'none'; vibrate 'none'; fullscreen 'none'; payment
    referrer-policy
    	same-origin
    retry-after
    	60
    server
    	cloudflare
    set-cookie
    	session_ruqqus=.eJwdzE0OwiAQBtC7fGsWxbbSchVjyOBMldgOBujCGO_uz_7lvRAeUjZS0Qbfyi4GTOUetswSRCmuwvDW4JZqy-UJf5pt784Ga74mDZr1IvCdQZVaU9aQvh5iiSnO_eQc8cEOo3S9HYiX5ehinCwM9irlj3_f-wOUcCxY.X12Cdw.4i3vVH0cJ1__pyRKAG4jyF5GHLI; Domain=.ruqqus.com; Expires=Mon, 13-Sep-2021 02:22:47 GMT; Secure; HttpOnly; Path=/; SameSite=Lax
    strict-transport-security
    	max-age=31536000
    vary
    	Cookie
    X-Firefox-Spdy
    	h2
    x-frame-options
    	deny
    x-ratelimit-limit
    	100
    x-ratelimit-remaining
    	99
    x-ratelimit-reset
    	1599963828
    	
    Accept
    	*/*
    Accept-Encoding
    	gzip, deflate, br
    Accept-Language
    	en-US,en;q=0.5
    Connection
    	keep-alive
    Content-Length
    	206
    Content-Type
    	multipart/form-data; boundary=---------------------------13222666974005735536540161990
    Cookie
    	session_ruqqus=.eJwdzE0OwiAQBtC7fGsWxbbSchVjyOBMldgOBujCGO_uz_7lvRAeUjZS0Qbfyi4GTOUetswSRCmuwvDW4JZqy-UJf5pt784Ga74mDZr1IvCdQZVaU9aQvh5iiSnO_eQc8cEOo3S9HYiX5ehinCwM9irlj3_f-wOUcCxY.X12CXg.OuiUDIk8tup0VQuE5DiTGHqjlIA; __cfduid=d69332f2d8d51500ce504ef4f92dce1091598835039; NB_SRVID=srv5268897; __cf_bm=4c44fe29d2dc21516e62ca06659666fe7a8b50e9-1599963202-1800-AQAyZZGjdWHEVyIE/AtWTm4HpNdDZcb7rBROOYeg0tUwoHI6MZ7lzQcWUPd1UbTMxra6TPey5sOqxHEN64eQjqw=
    Host
    	ruqqus.com
    Origin
    	https://ruqqus.com
    Referer
    	https://ruqqus.com/@IsaiahIsacc765
    TE
    	Trailers
    User-Agent
    	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0

**Comment by CrystalVulpine** [comment]
@PauloBoks 409 error means the follow relationship already exists, so it *should* mean that the follow was successful and you are indeed already following them. Probably just a display bug with the private profile pages.

Also, what "devtools console" are you talking about? I've never heard of it, is this another one of the admins' secret features only available to chosen users?

**Comment by PauloBoks** [comment]
@CrystalVulpine it's the browser console, but not the global one, the per page one (open inspect element and whatever)

not a web dev, not sure about all this stuff, on firefox it says "Developer tools" and i remember someone calling it "devtools" once lol
