### ISSUE TITLE
Make UX for uploading images easier to use/more inuitive

### ISSUE THREAD

**Issue by DGKSK8LIFE** [ruqqus/ruqqus#476]

**Comment by kek7198** [comment]
I'd like to support imgur-style uploading in the near-future

**Comment by DGKSK8LIFE** [comment]
@kek7198 I was told by the devteam a month or 2 ago that you guys were already using s3 to store images/host them for your app. After posting for the first time, I see that is not the case.

**Comment by kek7198** [comment]
@DGKSK8LIFE @captainmeta4 anything change with how images are stored?

**Comment by DGKSK8LIFE** [comment]
@kek7198 you should implement uploading directly within the app and store the images on your servers/s3 instances. Imgur is great to an extent put a pain in the ass for end users if they want to make a simple guild post without going full reddooooooooooot mode.
