### ISSUE TITLE
A list is not created when the numbers are formatted in any way.

### ISSUE THREAD

**Issue by vxern** [ruqqus/ruqqus#477]
Issue tracker is **ONLY** used for reporting bugs.

If I create a list but want to bold the numbers, underline them, or format them in any way, a list will no longer appear

## Expected Behavior

Formatting numbers should not affect list creation

## Current Behavior

A list indentation is not made.

## Steps to Reproduce

1. Make a list by writing numbers like this:

> 1.
> 2.
> 3.

2. Format the numbers:

> _**1.**_
> **_2._**
> _**3.**_

## Context (Environment)

I wanted to create a list for the rules for my guild, but instead the list was treated as normal text.

## Detailed Description

A list should be made no matter the formatting on the numbers

**Comment by ForeverZer0** [comment]
Have you tied using HTML directly? There is some limited support for that, bu it's definitely hit or miss, usually miss. I am not personally familiar with any Markdown flavors that support the syntax you propose, though GitHub flavor is pretty much the only kind I use on a normal basis.

**Comment by devongalat** [comment]
> Have you tried using HTML directly? There is some limited support for that, bu it's definitely hit or miss, usually miss. I am not personally familiar with any Markdown flavors that support the syntax you propose, though GitHub flavor is pretty much the only kind I use on a normal basis.

Heyo, it may be possible to use HTML directly, though a typical user should not be required to use HTML in order to do some regular formatting. It's just a QOL change.

**Comment by DGKSK8LIFE** [comment]
Agreed @devongalat
