### ISSUE TITLE
Provide identity proofs to Keybase

### ISSUE THREAD

**Issue by Foxite** [ruqqus/ruqqus#480]
Keybase.io is a website that lets people verify each other's identities by letting people post cryptographic signatures (proofs) on other websites, primarily on social media profiles they control. Because the proofs are cryptographic, there is no need to trust Keybase when verifying someone's identity. It has some more features, but I won't get into them here.

It already has support for a large number of websites, including Github, Reddit, Twitter, Hacker News, and several hundreds more. I suggest we add Ruqqus to the list.

Of course, a significant amount of our users are entirely opposed to this idea in the name of privacy, but I don't see how adding this feature would hurt the privacy of people who don't use it.

**Describe the solution you'd like**
[This page](https://book.keybase.io/guides/proof-integration-guide) has all the info needed to get it working. The most important thing is the configuration object, which has everything Keybase needs to know to verify someone's identity. The page I linked has an example config object that you can just fill in. There are a few things that need to be done, before we can use it:

* [x] Have [a guild where people can post their proofs](https://ruqqus.com/+KeybaseProofs)
* [ ] Provide a black version of our logo (presumably to display on a white background, which I suppose our porpl logo is fine for)
* [ ] Provide SVG versions of our [logos](https://ruqqus.com/help/press)
* [ ] Provide an API for Keybase (or anyone else) to verify the identities automatically. This is consists of a few JSON endpoints that Keybase clients will access. The endpoint could simply be a script that checks if a user has made a post in the aforementioned guild - there does not need to be a new database column for this.

**Comment by captainmeta4** [comment]
Identity verification is possible via the oauth `GET /identity` api, which requires the `identity` scope. Should be possible now.
