### ISSUE TITLE
Clicking links within crossposts breaks them

### ISSUE THREAD

**Issue by Frosty-J** [ruqqus/ruqqus#483]
If you don't know what I'm on about, we can take https://ruqq.us/3ga0 as an example of a crosspost. Nevermind its contents - this is just the most recent example I've seen.

You should see that there's a post embedded within this post. Clicking on internal links within the embedded post (e.g. the author's username, the number of comments) should result in your browser saying something along the lines of being unable to get the page.

In Chrome, this results in the following error in the JS console:  
`Refused to display 'https://ruqqus.com/...' in a frame because it set 'X-Frame-Options' to 'deny'.`

## Expected Behavior
Things to not break.

## Current Behavior
The browser becomes sad.

## Possible Solution
Disable these internal links and make clicking anywhere within the embedded post take you to that post's respective page.

## Steps to Reproduce

1. Go to https://ruqq.us/3ga0 or any other crosspost parent.
2. Click an internal link on the child, e.g. author name.

**Comment by lithiumjs** [comment]
Can reproduce.
