### ISSUE TITLE
User token verif

### ISSUE THREAD

**Issue by SuperLeaf1995** [ruqqus/ruqqus#485]
**Is your feature request related to a problem? Please describe.**
token in oauth

**Describe the solution you'd like**
a user can request that their bot be verified
and then the application token changes to become a verified application token
so when you request to oauth/grant anytime, it will say that the token is verified and won't return a refresh token, that access token will be valid until another one is generated under the verified token

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by SuperLeaf1995** [comment]
edit it to say that you dont need an authcode
just the token

**Comment by captainmeta4** [comment]
Not how oauth works
