### ISSUE TITLE
New line while commenting doesn't display on the next line when posted.

### ISSUE THREAD

**Issue by Pooja-novice** [ruqqus/ruqqus#515]
Issue tracker is **ONLY** used for reporting bugs.

## Expected Behavior

Hi
How are you

## Current Behavior

Hi How are you

## Possible Solution

I'm still learning so I'm not sure. I know dated \n XD

## Steps to Reproduce

I posted a comment in response to one of my posts but I'm sure that can be replicated anywhere. It works fine on new posts but not on comments.

1.
2.
3.
4.

## Context (Environment)
 better readability

**Comment by lithiumjs** [comment]
The issue you described is part of a markdown spec. Not a bug.
