### ISSUE TITLE
Cannot paste a url of an image

### ISSUE THREAD

**Issue by Pooja-novice** [ruqqus/ruqqus#516]
Issue tracker is **ONLY** used for reporting bugs.

## Expected Behavior

I should be able to access my clipboard and paste

## Current Behavior

Paste comes up but nothing happens. I also can't access my clipboard. It's not used friendly typing the url no matter how short it is. At least not on the phone. 

## Possible Solution

Possibly allow paste and accessing clipboard

## Steps to Reproduce
 
Copy a link and paste it in the url field 

1.
2.
3.
4.

## Context (Environment)

Since I do not have the required reps to upload an image yet.. it is a temporary issue. Nonetheless is one until I reach there.

**Comment by captainmeta4** [comment]
This is an issue with your OS/browser, not Ruqqus

**Comment by Pooja-novice** [comment]
I use the app.

**Comment by Pooja-novice** [comment]
Also, paste works fine into the description.. just not the url field. Other
users complained of the same issue so I logged it on github.
Not sure if anything is going to happen of this since you closed the ticket?
Anyway, I was just trying to help.
