### ISSUE TITLE
Whitespace in email validation URI.

### ISSUE THREAD

**Issue by Kuinox** [ruqqus/ruqqus#518]
Issue tracker is **ONLY** used for reporting bugs.

![image](https://user-images.githubusercontent.com/18743295/97374820-8851a300-18b9-11eb-837c-df778d66b974.png)

## Expected Behavior
No space so it's a valid URI.

## Current Behavior
A space char is inserted after the domain name.
https://github.com/ruqqus/ruqqus/blob/master/ruqqus/mail/mail.py#L38  
From this code, it looks like a space got accidentally appended in the environement variable.

## Possible Solution
Check the environement variable of the server and remove the trailing whitespace.

## Steps to Reproduce
1. Create an account
2. Receive the account validation email

## Context (Environment)
Was trying to validate my email, looks like the button doesn't works (thought it was my aggresive ad blocker):
![image](https://user-images.githubusercontent.com/18743295/97375091-34938980-18ba-11eb-9fcc-99bb00b8e945.png)
Looks like the link don't contain any href, is this intended ?

**Comment by Kuinox** [comment]
Found the template, and looks like there is an issue there too: 
https://github.com/ruqqus/ruqqus/blob/1d83e4aa8d571096bc16ae81e7ae013156fde1ff/ruqqus/templates/email/email_verify.html#L18

**Comment by lithiumjs** [comment]
Should be fixed in f75ff52.
