### ISSUE TITLE
Exiling a previously pardoned user does not give the user a notification

### ISSUE THREAD

**Issue by dginovker** [ruqqus/ruqqus#536]
## Expected Behavior
If exiled, then pardoned, then exiled again, the exiled user should receive a notification for the second exile. Right now they don't (it might be an anti-spam thing?)

## Current Behavior
The exiled, pardoned, then re-exiled user only receives one notification

## Possible Solution
* Keep it as it is to prevent abuse
* Add a throttle for how quickly you can exile a user after pardoning them

## Steps to Reproduce
1. Make a 2nd account
2. Head to https://ruqqus.com/+yourfavoriteguild/mod/exiled 
3. Exile the 2nd account
4. Pardon the 2nd account
5. Exile the 2nd account again
6. Go to notifications on 2nd account, view only 1 exile message

**Comment by captainmeta4** [comment]
As designed - we do not want the exile message to be used to spam
