### ISSUE TITLE
Improve the dark theme of Ruqqus alongside certain UI/UX elements that only look good in the default light mode.

### ISSUE THREAD

**Issue by RyuSantiago** [ruqqus/ruqqus#544]
I originally raised this issue in +Ruqqus through [this post](https://ruqqus.com/+Ruqqus/post/4ism/an-important-ui-suggestion) in question and was suggested to submit directly to its repository where it's more likely to be seen by the contributors and developers of Ruqqus.

I'll summarize what I brought up originally in the initial post made in +Ruqqus:
The general experience of using Ruqqus in dark mode is slightly degraded since certain UI and UX elements are either optimized poorly for dark mode or aren't optimized on at all.

My solution was to improve the readability of these unoptimized elements through simple text color tweaking [(with my examples having the text in the Shortlink element being changed to the dark mode's sidebar colors)](https://mega.nz/folder/NY9ElKAK#-FRg9b5zK4xRUNTsnfk12w) and for some guilds, colors using the light mode's colors rather than the pastel-looking (some might say washed out) versions the dark mode uses.

Some guilds do retain general contrast balance and text readability in dark mode, so for those colors, the white text can still be used with little issue. However, for certain guilds with vibrant colors the darker text color should be used.

This issue along with these suggestions can also be adapted to general usage in other elements such as the Previous and Next buttons among other things.

**Comment by kek7198** [comment]
I'm working on improving dark mode in the vue update with utility classes similar to Tailwind

**Comment by RyuSantiago** [comment]
> I'm working on improving dark mode in the vue update with utility classes similar to Tailwind
Glad to hear that, I felt that it was an important (although not as much as site stability and performance) issue to bring up to improve the interface.

**Comment by RyuSantiago** [comment]
[Here's another small discrepancy with dark mode on Ruqqus, this time with the random viewer button.](https://streamable.com/0b77xf)
