### ISSUE TITLE
Add ability for admins to define rules and ban users based on what rule they broke

### ISSUE THREAD

**Issue by Wingo5315** [ruqqus/ruqqus#547]
**Is your feature request related to a problem? Please describe.**
When you are banned from a guild, there isn't an opportunity for admins to tell the user what rule they broke. Here is the current message:

![image](https://user-images.githubusercontent.com/25369857/98462690-082b1780-21ae-11eb-8f6f-76927172796e.png)

**Describe the solution you'd like**
Guildmasters should be able to define the rules of the guild, which should be displayed in a similar way to Ruqqus' Rules and Guidelines on the post creation page:

![image](https://user-images.githubusercontent.com/25369857/98462768-81c30580-21ae-11eb-9418-75e9f339b325.png)

The message sent to banned users should therefore look something like this:
![image](https://user-images.githubusercontent.com/25369857/98462756-67892780-21ae-11eb-8a4f-1c6fbbcf0a82.png)

**Describe alternatives you've considered**
You could rely on guildmasters to reply to the user's comment/post saying they were banned for X reason, but this shouldn't be on the guildmaster to do this.

**Additional context**

**Comment by lithiumjs** [comment]
Coming in Vue Update.
