### ISSUE TITLE
potential issue with the spam filter

### ISSUE THREAD

**Issue by Deauthorized** [ruqqus/ruqqus#552]
https://github.com/ruqqus/ruqqus/blob/4de33bca7f376a76c8c6fac7090e52c95870ac64/ruqqus/routes/comments.py#L302

haven't tested this out myself yet but judging by this line if i were to set my useragent to "" would that mean the spam filter would no longer apply to me?

**Comment by CrystalVulpine** [comment]
No, judging by how these methods usually work in python, this means that if there is no `X-User-Type` then it returns '""' by default, which does *not* equal '"Bot"'.

**Comment by lithiumjs** [comment]
@CrystalVulpine is correct. The only way you can bypass spam filter is by setting your `X-User-Type` header to `Bot` while commenting. `User-Agent` is not related to that in any way.
