### ISSUE TITLE
Buncha feature requests for the API

### ISSUE THREAD

**Issue by danhab99** [ruqqus/ruqqus#553]
Ok so in my efforts to build a standalone app for this api I have discovered some holes in the api coverage so I'm just gonna outline the ones I'm aware of here. If you have any I didn't include please post them in a comment.

1 **Implicit OAuth!!!** The alternative (which I've researched) is to have a 3rd party authing server that would request the tokens from ruqqus then send them to the user, which is insecure. The other alternative is to compile the client secret into the app which is unacceptable. Currently what my app does is give instructions on how to apply for your own client id & secret, which is fine for me rn while I'm developing... can't imagine a plan like that would scale tho.

2. An endpoint for retrieving the comments of a post given a post ID. Right now there's an endpoint that just gets the comments that have been posted to a guild given an ID. And each comment has the id of it's parent post. But it doesn't make sense because querying it gives no guarantee that you got all the comments for a post.

3. An endpoint for notifications. Push notifications would be absolutely golden but it's not necessary. Just an endpoint that can be queried once an hour that just returns an array of comments is enough.

4. The  `api/v1/identity` endpoint should include the guilds I'm subscribed too

5. An endpoint for searching for guilds by name, not 100% necessary but it could be nice

6. An endpoint for guild discovery. Again, not 100% necessary.

**Comment by danhab99** [comment]
7. An endpoint for retrieving a feed of my subscriptions. Currently we have `api/v1/front/comments` and `api/v1/all/listing` which don't really help.

8. Fetching `https://ruqqus.com/api/v1/guild/<guild name>` returns no indication as to if I'm subscribed to that guild

**Comment by danhab99** [comment]
9. Fetching a post shows no indication that it's pinned

**Comment by kek7198** [comment]
> 1. Fetching a post shows no indication that it's pinned

I think is_pinned has been added by @arkit3kt

**Comment by Shatterbrain** [comment]
@danhab99 
If I understand correctly, the direction you want to take with Implicit Grant is to redirect to `localhost` to capture the token without using a third party server? How are you going to redirect to `localhost` via `ssh`? Generating a self-signed certificate?

Why do you think it would be insecure to "have a 3rd party authing server that would request the tokens from ruqqus then send them to the user"? 

I know it's been a while since you posted this so you may have lost interest since then. But I'm running into similar architectural questions and need to decide what the ideal way forward would be so I know what to advocate for. And my use case sounds quite similar to yours.

**Comment by danhab99** [comment]
> @kek7198 
> > 1. Fetching a post shows no indication that it's pinned
> 
> I think is_pinned has been added by @arkit3kt

I do not see an `is_pinned` in current api requests, nor do I see any mention of pinning in @acikek 's wrapper. [example.txt](https://github.com/ruqqus/ruqqus/files/5761205/example.txt)


> @Shatterbrain 
> If I understand correctly, the direction you want to take with Implicit Grant is to redirect to localhost to capture the token without using a third party server? How are you going to redirect to localhost via https? Generating a self-signed certificate?

So from what I understand about implicit oauth is that it cuts out the `client_secret` requirement, delivering the access and refresh tokens in a response from the server, there's no need for a redirect, the app would beable to do it by itself.

> Why do you think it would be insecure to "have a 3rd party authing server that would request the tokens from ruqqus then send them to the user"?

It's insecure because there is an instant where me (though my server) possesses an access token for a random user in the authing server's memory. This is necessary so I can then transmit it to the requesting user-agent. But there is no guarantee that I'm not logging that token, or using it for malicious purposes, beyond my promise. Having a third party authing server exposes a vulnerability in the oauth procedure that isn't necessary. Also, I have to pay to keep the server up... which I don't want to do.

> I know it's been a while since you posted this so you may have lost interest since then. But I'm running into similar architectural questions and need to decide what the ideal way forward would be so I know what to advocate for. And my use case sounds quite similar to yours.

Uhh I'm not loosing interest for a fat minute boii. I'm still here. Implicit oauth is meant for client side applications, if you're looking to build a bot you have no need beyond 3-legged-oauth because you can control 2 of the legs. Unless you're building your own 3rd party client?

**Comment by danhab99** [comment]
I'm just gonna quickly revive this thread with some more holes I've found.

10. Post replies (and all comments) show no indication as to how it has been voted on. See example: [example_ad6u.json.txt](https://github.com/ruqqus/ruqqus/files/6408776/example_ad6u.json.txt)
11. Post replies show no indication of being pinned
12. `api/v1` cannot subscribe to guilds. See [how I've been identifying `api/v1` endpoints](https://github.com/ruqqus/ruqqus/search?q=api%2Fv1)
13. `api/v1` cannot retrieve the inbox/notifications

**Comment by danhab99** [comment]
Ammendment. 

* Point 2 resolved
* Point 7 is moot, ignore
* Point 3 and 13 are the same, ignore one of them

**Comment by danhab99** [comment]
Point 9 resolved

**Comment by danhab99** [comment]
Closing because nobody cares I guess


---

Also my retrospective:

TBH around the time I got booted from Reddit and joined Ruqqus I was already kinda growing disolutioned with the "message board" type of social media. Shit got boring, people were single minded and the kind of content I enjoyed wasn't all that popular. It was hard to engage with people and when I did it wasn't that much fun. But I found my niche way of enjoying Ruqqus, there were no nice 3rd party apps that allowed me to customize my mobile experience (which is how I'm on the internet 90% of my free time because I don't have to wear my glasses that I hate when I'm on my phone), so I set off to develope [Scroll For Ruqqus](https://github.com/danhab99/scroll-for-ruqqus) and I had alot of fun doing it. I'm a goal oriented person and I don't learn things unless I *need* to, so SFR was a great reason to learn React Native for me. But my attention was thrown every which way and after I completed a bulk of the feature set fixing small blocking-bugs wasn't as fun. I started focusing on different projects and recently I got hired for my first junior position where I get to use all the React Native skills I acquired from SFR. That compounded with the antisemetic (I'm jewish) homophobes (also gay) didn't really make Ruqqus fun for me. 

Thanks @captainmeta4, @kek7198, and everybody else for bootstrapping the amazing project, it was fun while it was and I hope to encounter all of you in the future, except for @Aevann1. After taking afew steps back I realized why others thought he was problematic and frankly rdrama.net is kinda really lame so I'm just going to seperate myself from *that*. I don't plan on working on SFR anymore, I'm just going to archive the repo and any plans to release to the App Store or Google Play are gone.

That being said I think free speech is one of the most important issues to discuss and we need a place where we can speak our minds. I've been inspired by Ruqqus, Reddit, Facebook and all the other platforms to take this issue on and I've been experimenting with a buisness model which profits from maximizing freedom of speech. I hope I can create a stable, long lasting, social media platform for all of us. 

I'm not prepared to release more details about it yet, but I do have something in the works and I hope to see you all there when it's ready.

In the wise words of a spek of dust:

# Goodbye Everyone, I'll Remember You All In Therapy
