### ISSUE TITLE
creating a post with some javascript code inside the `href` attribute of `a` tag results in a 500 internal server error

### ISSUE THREAD

**Issue by volatileColors** [ruqqus/ruqqus#556]
creating a post with some javascript code inside the `href` attribute of `a` tag results in a 500 internal server error.
Example: `<a href="javascript:alert('hi there!');">click here</a>` creating a post with this as the body will result in a 500 internal server error.

## Expected Behavior
Should escape the text properly and treat the line of code as a literal string or at least show a message to the user that their post body is invalid.

## Current Behavior
Results in a 500 internal server error

## Possible Solution
Escaping the post text body properly.

## Steps to Reproduce
1. Click on create a new post
2. Put anything in the title field. Put `<a href="javascript:alert('hi there!');">click here</a>` in the body field.
3. Click post button

**Comment by captainmeta4** [comment]
Fixed on dev
