### ISSUE TITLE
Custom filter(s)

### ISSUE THREAD

**Issue by cdhomels** [ruqqus/ruqqus#558]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
A custom filter that operates exactly like the Offensive Speech filter, that allows you to filter posts/comments based on custom words (and maybe allow regex patterns for more complex filters?). I have already seen a Politics filter requested, and that could be used as an example as why this feature would be useful (also maybe allow contributing for preset filters, so users don't have to compile - for example - political words.)

**Describe alternatives you've considered**
This could be extended further by allowing to create mutiple filters targeting different topics, so you can disable/enable them without affecting the other topics.
If we want to take it a step futher, integrating the filters in the front page instead of solely in the settings.

**Additional context**
None.

**Comment by kek7198** [comment]
This is under development

**Comment by lithiumjs** [comment]
Resolved in #560.
