### ISSUE TITLE
Exiles should only last 30 days

### ISSUE THREAD

**Issue by dginovker** [ruqqus/ruqqus#561]
**Is your feature request related to a problem? Please describe.**
It is [clear](https://ruqqus.com/+OpenLeft/post/4y8a/the-price-of-free-speech/h4cx) that some users are using Ruqqus' exile function in a way that might seem a little abusive. Exiling trolls or gross abusers is great, but when the trolls are the ones running large guilds, it causes problems.

**Describe the solution you'd like**
Exiles should be temporary only - a set limit of 30 days rather than permanent.

**Describe alternatives you've considered**
* Option to permanently exile repeat offenders
* Creating alternative guilds

**Additional context**
[+LeMemery](https://ruqqus.com/+LeMemery) was basically created out of disgust for the abuse of the exile function. I've seen the idea of temporary exiles being brought up a number of times on Ruqqus, and the only opposition I've seen are from people who think the exile function shouldn't exist all together.

**Comment by mcouyoute** [comment]
I think the site should maintain it's 30 day rule to see if any positive change will come from it. With the rise of people migrating away from social media due to censorship, the site will most likely gain trolls. However, trolls may slowly leave due to bordem when they realize that they have to wait 30 days participate.

**Comment by dginovker** [comment]
Why close

**Comment by Mr-Steal-Your-Script** [comment]
No, I think 30 days is too short of an amount of time. 60 days at least. I also think that this should be fixed:

- Post is in +general

- "Guild Master" can "yank" the post to their guild

- Guild Master can now ban the OP of the post and all the users that commented on it

This can easily be abused.

**Comment by kaijuagenda** [comment]
Probably because a forced temp limit takes functionality away from the guildmaster role to start.

Would be better off having the option to exile with an optional amount of time (hours, days, etc.) 

This can totally be up to the guildmaster already, but they have to track it themselves.

**Comment by dginovker** [comment]
> Probably because a forced temp limit takes functionality away from the guildmaster role to start.
>
> Would be better off having the option to exile with an optional amount of time (hours, days, etc.)

Guild masters should have less power to abuse, not more
