### ISSUE TITLE
Ruqqus Coin receive text automatically says it was traded for 1 week of Ruqqus Premium, even if it wasn't

### ISSUE THREAD

**Issue by dginovker** [ruqqus/ruqqus#564]
When getting a Ruqqus Coin, if you have no Premium, you get 1 week of Ruqqus Premium
If you have Ruqqus Premium, you get 1 coin

## Expected Behavior
Message should say something like

```
Someone liked your post and has given you a Coin!
This Coin will automatically redeem for one week of Ruqqus Premium when your current Premium expires.
```

## Current Behavior
You get a message saying

```
Someone liked your post and has given you a Coin!
Your Coin has been automatically redeemed for one week of Ruqqus Premium.
```

## Possible Solution
Include a way to say you can spend the second coin - although it's very late and I can't think of a concise way to word it.

## Steps to Reproduce
1. Get a tip
2. Get another tip while premium is still running

**Comment by captainmeta4** [comment]
Fixed. I had the logic inverted -_-
