### ISSUE TITLE
It says subs instead of guilds when you search for guilds

### ISSUE THREAD

**Issue by IsaiahIsacc765** [ruqqus/ruqqus#575]
change  sort = request.args.get("sort", "subs").lower()
to 
sort = request.args.get("sort", "guilds").lower()

https://github.com/ruqqus/ruqqus/blob/master/ruqqus/routes/search.py
there's a link to where the sorting thing is

**Comment by captainmeta4** [comment]
that's sorting guilds by subscriber count
