### ISSUE TITLE
Suspending or unsuspending an account removes profile picture and banner

### ISSUE THREAD

**Issue by CrystalVulpine** [ruqqus/ruqqus#583]
Not sure whether it's when someone gets suspended or unsuspended, but their profile picture and banner are deleted. It has to be manually reuploaded afterward.

**Comment by CrystalVulpine** [comment]
Will be fixed by #584

**Comment by lithiumjs** [comment]
I'm sure that's intentional.

**Comment by CrystalVulpine** [comment]
Why would that be intentional? I feel like the admins just unthinkingly copied and pasted the code for deleting an account (though I'm almost always wrong because I'm stupid). Accounts *do* get unbanned you know, and you can even upload a new avatar and banner while you're suspended, it just deletes the one you had prior.

**Comment by arkit3kt** [comment]
I believe our thinking for this initially was those items were likely to be a problem when banning the user, maybe we should change for standard suspension. @captainmeta4 

Also, i wouldn't say you're stupid @CrystalVulpine, by just participating on github you're smarter than a lot more people than you probably think lol.

**Comment by CrystalVulpine** [comment]
> Also, i wouldn't say you're stupid @CrystalVulpine, by just participating on github you're smarter than a lot more people than you probably think lol.

That's called being ambitious. Smart is someone like sfrohne who is automatically god-level at everything and knows absolutely everything even on the first try. Stupid is someone like me who despite years of persistence can never manage to master even a single thing or know very much.
