### ISSUE TITLE
Change "Guild Banner" upload text to specify dimensions rather than 1060x250 pixels

### ISSUE THREAD

**Issue by dginovker** [ruqqus/ruqqus#588]
**Is your feature request related to a problem? Please describe.**
After spending several hours crafting a beautiful 1060x250 pixel banner, I realized it looks like it got stretched from here to China across a 16 inch monitor. I then spent roughly half the time developing a 4240*1000 banner (multiply both dimensions by 4) and it looked crisp as a winter's day.

**Describe the solution you'd like**
Change the text `JPG, PNG, GIF files supported. Max file size 16MB. (Recommend 1060x250 pixels)`, found in https://ruqqus.com/+YourBossGuild/mod/appearance, to `JPG, PNG, GIF files supported. Max file size 16MB. (Recommend ratio of 1060x250)`

**Describe alternatives you've considered**
Letting everyone else suffer 

**Additional context**
I don't speak leet graphics so if there's better wording use that obviously

**Comment by ruqqusBanido** [comment]
also there is no actual limit on the upload apart from nginx, so you can upload up to 64mb profile and guild banners

**Comment by kaijuagenda** [comment]
Could also define the ratio of the image instead of pixel measurements, 106:25
