### ISSUE TITLE
Suggestion for information density.

### ISSUE THREAD

**Issue by anonymous-jack** [ruqqus/ruqqus#590]
I have found that I much prefer websites with high information density to websites with low information density. On my desktop, hackernews shows 18 links, and old reddit shows 10 links. I find this efficient because you can skim through many links without scrolling.
![hackernews](https://user-images.githubusercontent.com/75923145/102004024-b1e45380-3cda-11eb-812f-287485e668ad.png)
![reddit](https://user-images.githubusercontent.com/75923145/102004037-db04e400-3cda-11eb-9423-ac69436cd35b.png)

Contrast this with new reddit (2 links):
![reddit_new](https://user-images.githubusercontent.com/75923145/102004051-23240680-3cdb-11eb-81ab-72ce0271201d.png)

I believe some of the backlash against the new reddit layout was caused by decreasing the number of links on the screen. This completely eliminated the ability for the user to skim through content without scrolling.

This is the current ruqqus layout (7 links):
![ruqqus](https://user-images.githubusercontent.com/75923145/102004067-5c5c7680-3cdb-11eb-8a68-78e04fdb4959.png)

While I appreciate the ability to search posts, filter, and sort, I think it impedes on the ability to skim content quickly because it reduces information density.

Proposed ruqqus layout (10 links)
![ruqqus_new](https://user-images.githubusercontent.com/75923145/102004130-f6242380-3cdb-11eb-8c5c-87a99a127835.png)

This layout eliminates padding between cards and freezes the search/homepage bar to the top. These changes allow for 42% more links. 7->10. 

I propose: switch to this layout or give the option in settings to switch to a high-information density mode.

**Comment by anonymous-jack** [comment]
I find this suggestion equally true for comments. Having more comments on a page greatly increases my ability to process a written conversation. I'm curious to see what other people think.

 This is the current layout (7 comments):
![comments_og](https://user-images.githubusercontent.com/75923145/102004628-89f7ee80-3ce0-11eb-8746-c1168f0ed85c.png)

New layout (10 comments):
![comments](https://user-images.githubusercontent.com/75923145/102004624-7ea4c300-3ce0-11eb-8b03-37827a628990.png)

**Comment by lithiumjs** [comment]
In my opinion, that would be way too much information crammed into a small space. I dunno though.

**Comment by arkit3kt** [comment]
I think 10 post/comments looks good, i'm fine with this.

**Comment by kek7198** [comment]
This is no possible with customized guild css. I can explore a third compact layout in Vue using dynamic components (instead of CSS). Closing this.
