### ISSUE TITLE
When I try to access guild setting of a new guild I get {"error":"Permission `config` required"}

### ISSUE THREAD

**Issue by 1ethanhansen** [ruqqus/ruqqus#606]
Issue tracker is **ONLY** used for reporting bugs.

## Expected Behavior
Since I was the one who created the guild, I figured I should have guild settings access

## Current Behavior
(Guild is [+FRC](https://ruqqus.com/+FRC) in case that helps)

From the Guild home page I click on the three dots, then the button for "Guild Settings." Then I get an error in the form of JSON saying {"error":"Permission `config` required"}.

Same thing happens if I manually copypaste the link into the browser (https://ruqqus.com/+FRC/mod/settings)

## Possible Solution
With the new changes to guildmasters' abilities, maybe when a guild is created, the guildmasters aren't given certain access that they should? Also maybe helpful to note: I tried accessing guild settings on other guilds I'm a GM for and those all worked. Those guilds were created before the recent changes.

## Steps to Reproduce
1. > be me
2. go to https://ruqqus.com/+FRC/mod/settings
3. profit

## Context (Environment)
I'm doing this through tor, maybe that's the problem? Haven't really had issues with tor before though

**Comment by captainmeta4** [comment]
Fixed
