### ISSUE TITLE
error package in requirements.txt

### ISSUE THREAD

**Issue by avidican92** [ruqqus/ruqqus#611]
https://github.com/ruqqus/ruqqus/blob/4b44f0ee5d38bc920db843925c371733b385719e/requirements.txt#L43

Hi, the line 43 generate an error
Could not find a version that satisfies the requirement pkg-resources==0.0.0 (from -r requirements.txt (line 43)) (from versions: )
No matching distribution found for pkg-resources==0.0.0 (from -r requirements.txt (line 43))

**Comment by mkay581** [comment]
Yeah same for me. Definitely blocks me from running the app locally.

**Comment by captainmeta4** [comment]
will fix for next release

**Comment by Shatterbrain** [comment]
Fixed in 0e4152c8a85c049207748d02ca98f24f8d66f5c3
@lithiumjs I think you can close this.
