### ISSUE TITLE
Exiled users should still be able to rep posts in guilds

### ISSUE THREAD

**Issue by dginovker** [ruqqus/ruqqus#615]
**Is your feature request related to a problem? Please describe.**
* Exiling function doesn't state otherwise
* Gives mods too much power 
  * i.e. exile everyone in a niche that would disagree with you, now your posts hit frontpage

**Describe the solution you'd like**
* Allow exiled users to rep

**Describe alternatives you've considered**
* Update the exiled text to remind users their vote is censored

**Comment by dginovker** [comment]
I know it's been discussed on Discord (without admins taking a side), but the more I think about it, the more silly I realize this is. Not even Reddit allows mods to have this sort of power :/

**Comment by CrystalVulpine** [comment]
@dginovker actually votes from banned users don't count on reddit, so they basically shadowban you. At least that's what the admins have always said, however I've tested with shadowbanned and subreddit banned accounts myself and can testify that the votes actually do count. There's also nothing about it in old source code (though that's from 2017).
