### ISSUE TITLE
Goal Percent going down despite buying more coins and giving them out

### ISSUE THREAD

**Issue by AldebaranIII** [ruqqus/ruqqus#624]
Goal Percent going down despite buying more coins and giving them out

Despite being the third time buying the 20 dollar coins bundle option within just a few weeks, my percent went from 94 to 97 then sharply down to 96 immediately after awarding 4 or 5 today alone so far!

![screenshot-ruqqus com-2021 01 03-12_49_22](https://user-images.githubusercontent.com/76915102/103485212-bfb16400-4dc2-11eb-9918-e2fecd9475f5.png)

**Comment by acikek** [comment]
![](https://media.discordapp.net/attachments/774344186773241906/777921448801992704/image0.png?width=536&height=779)

**Comment by captainmeta4** [comment]
what @acikek said
