### ISSUE TITLE
Siege of masterless guild fails

### ISSUE THREAD

**Issue by Benandorf** [ruqqus/ruqqus#639]
I attempted to siege the guild +marvel, which is listed as having no guild master, and it failed to siege. I hadn't started my 30 day cooldown, so can't see any reason why the siege would fail except that the code does not allow a masterless guild to be sieged for some reason, so I think this is a bug/oversight in how the siege process works.

**Comment by CrystalVulpine** [comment]
It may have a deleted guildmaster or something. I haven't checked for this particular situation but the logic with that is fairly inconsistent.

**Comment by Benandorf** [comment]
Any update to this?

**Comment by vulpinefoxxo** [comment]
does this still occur?
![image](https://user-images.githubusercontent.com/68159867/116197819-b73fb900-a724-11eb-83f1-61f8b71f7eb2.png)
i see some comments that look like TODOs so if it still occurs i can try add something
