### ISSUE TITLE
Make Bot Token Issuance Automatic

### ISSUE THREAD

**Issue by dginovker** [ruqqus/ruqqus#640]
*This is a confirmed thing captainmeta4 wants/will approve: https://i.imgur.com/mozU2zQ.png*

In https://ruqqus.com/settings/apps you can "Request API Keys", which an admin has to approve before you get your Client ID and Client Secret. For the sanity and motivation of app developers, this request should be replaced with a "Generate" instead that immediately gives you tokens

**Comment by kek7198** [comment]
API access is restricted for to mitigate abuse. Maybe we could allow for automatic generation but restrict bot access. Admin dashboard will need a proper UI for API access overview though (revoking access to bad actors).
