### ISSUE TITLE
"undefined" alert when joining a guild

### ISSUE THREAD

**Issue by aarivex** [ruqqus/ruqqus#642]
I had two tabs open, one being a post from a specific guild and the other being the main page of the guild.
I joined the guild over the main page and attempted to join it again on the other tab, which, in that time, still had the state of being unsubscribed, because I forgot about it.

This triggered an alert with "undefined".

## Expected Behavior
Show an error telling that this guild is already subscribed to or an unexpected error occured.

## Current Behavior
Stated above.

## Possible Solution
Check the state of subscription each time someone attempts to join a guild, maybe via REST, or at least catch the exception.

## Steps to Reproduce
1. Open two tabs with either the main page of an guild or some content that was posted within that guild.
2. Join the guild from one of the tabs.
3. Attempt to join the guild a second time from the other tab.

![firefox_wVN2wLOLZG](https://user-images.githubusercontent.com/18628875/105115631-7737bd00-5ac9-11eb-9072-0a3bae0ab06b.png)

## Context (Environment)
Just a minor bug, but should be fixed.

**Comment by vulpinefoxxo** [comment]
![image](https://user-images.githubusercontent.com/68159867/116196083-8fe7ec80-a722-11eb-9084-0ea8df900d57.png)
message is already there, just needs to be displayed
