### ISSUE TITLE
You can only create 1 guild a day (instead of 2)

### ISSUE THREAD

**Issue by dginovker** [ruqqus/ruqqus#648]
## Expected Behavior
When creating 2 guilds within 1 day, you shouldn't see "You can only create up to 2 guilds per day. Try again later."

## Current Behavior
You seem to get that message - Now I looked at the code and I don't see how this can be, the check explicitly checks for >= 2. Not sure what's up, maybe a recent update broke it entirely and you can only create 1 guild permanently? Idk

## Steps to Reproduce
1. Create a guild
2. Create another guild

Big Sad!
![image](https://user-images.githubusercontent.com/32943174/105530355-a90d7700-5cb5-11eb-9140-4cd9625f52a1.png)

**Comment by IThinkImOKAY** [comment]
I was just able to create 2 guilds today. How many guilds do you moderate?

**Comment by captainmeta4** [comment]
It's a rolling 24 hour period, irrespective of whenever midnight is for you. Working as intended.
