### ISSUE TITLE
Please provide a fully docs to set it up

### ISSUE THREAD

**Issue by aldemy** [ruqqus/ruqqus#658]
After the compose is done with no errorsit doesn’t work properly.

Cannot pass the Welcome page no matther what I select. If I try to login or sign up I’ve get the “Internal server error” message.

Probably because I have to setup all the keys in the yml file, but I don’t know how.

**Comment by Panjkrc** [comment]
Here are the new install instructions for Linux
https://github.com/ruqqus/ruqqus/wiki/Installation-instructions-for-Linux

Master branch is broken so you will have to use https://github.com/ruqqus/ruqqus/pull/773 if you want to run ruqqus
