### ISSUE TITLE
Remove https forcing on external links

### ISSUE THREAD

**Issue by n8jadams** [ruqqus/ruqqus#667]
It seems like in the `a_modify` function in `ruqqus/ruqqus/helpers/sanitize.py`, Ruqqus forces links to have the https protocol.

Why is this? As far as I'm aware, there's no penalty for _linking_ to an http website. It's only problematic when you use assets on a page (such as images, videos, loaded scripts, css, etc.) with the http protocol if your site is under https.

It sucks that not everyone is on https yet when services like Certbot or LetsEncrypt make it very easy, but the experience for people linking to sites that break on https but work on http is confusing people.

I'm not sure if the problem is isolated in that `a_modify` function, which is why I didn't make a PR. But ultimately I'd like to see the protocol respected (at least http/https) when users link to a website and an anchor tag is put on the page in posts or comments.

**Comment by dginovker** [comment]
Possibly related to #644

**Comment by captainmeta4** [comment]
This measure is in place for user safety. It is 2021, there is absolutely zero excuse to *not* have an SSL certificate in place, especially when services like cloudflare offer free SSL termination.

**Comment by n8jadams** [comment]
That's assuming that you're knowledgable enough to know you need it, technical enough to set it up yourself, or have the means to have someone else set it up for you. For example, is https really necessary for a blog post?

The only thing you need to do to protect users when linking to external websites is cover their tracks on the page their visiting, i.e. making sure there's a `rel="noopener"` or `rel="noreferrer"` set on your anchor tags. https://web.dev/external-anchors-use-rel-noopener/

Sending people to non-existent websites might give you a better lighthouse score, but it's a bad UX because people click links to websites that are hosted on http, but are a dead page on https. There's an inherent security risk in clicking on external links, and forcing https doesn't mitigate that risk at all.
