### ISSUE TITLE
Ruqqus APIs are behind (and do not bypass) Cloudflare

### ISSUE THREAD

**Issue by drvladb** [ruqqus/ruqqus#670]
## Expected Behavior

When querying an API, the request should not trigger a security challenge and be passed to the origin.

## Current Behavior

When calling an API too many times from a single IP, Cloudflare presents the security challenge instead of the API response.

## Possible Solution

Introduce a Cloudflare Page Rule that will pass api requests to the origin instead of caching / browser checking them.   
I.E: 
![image](https://user-images.githubusercontent.com/33793511/107297733-f291ec00-6a41-11eb-974a-942132304734.png)

## Steps to Reproduce

1. Make a large (100+) requests to the Ruqqus API
OR
1. Set the "Under Attack Mode" to On
2. Make a request to the Ruqqus API

### Response (if you cant reproduce)
This is what a request returns when the bug is triggered
[ruqqusCall.txt](https://github.com/ruqqus/ruqqus/files/5947720/ruqqusCall.txt)

## Context (Environment)

I am working on a small project with the Ruqqus API and am encountering errors when calling the API that when the content is examined are Cloudflare security checks (which a regular API client is unable to complete)

## Detailed Description

Add a method by which API requests will be passed to the origin

## Possible Implementation

One way to do this (from Cloudflare):
Create a new Cloudflare Page Rule like this one:
![image](https://user-images.githubusercontent.com/33793511/107299165-bad87380-6a44-11eb-9970-c9638aede834.png)
![image](https://user-images.githubusercontent.com/33793511/107299052-9aa8b480-6a44-11eb-8e29-cebdb68f4e98.png)

## Additional Reading
[https://support.cloudflare.com/hc/en-us/articles/200504045-Using-Cloudflare-with-your-API](https://support.cloudflare.com/hc/en-us/articles/200504045-Using-Cloudflare-with-your-API)

**Comment by Deauthorized** [comment]
api requests should be from a valid bot or else that leaves the site open to ddos attacks

**Comment by drvladb** [comment]
@Deauthorized, Agreed, but even requests from legitimate users are caught in the filter. To prevent DDOS attacks (against the API), a system that doesn't brick normal users traffic should be used. If you have a suggestion how to do it on Cloudflare, please share it with me.

**Comment by IThinkImOKAY** [comment]
Are you properly authenticated? I have created [`raw`](/raw-dev/raw) and use it daily. Never seen such a response, despite making calls about every 30 seconds.

**Comment by captainmeta4** [comment]
/api/v1 endpoint set to Security Level Low
