### ISSUE TITLE
Sort "My Guilds" by guilds with a most recent post!

### ISSUE THREAD

**Issue by dginovker** [ruqqus/ruqqus#673]
*Section in question*
![image](https://user-images.githubusercontent.com/32943174/108648361-03eae780-7489-11eb-8e27-6b8d35f04dcb.png)

**Is your feature request related to a problem? Please describe/Describe the solution you'd like/Other stuff**
1. My Guilds currently has an unbeneficial order
2. You'll be reminded of niche guilds that don't hit your Front Page often
3. Gives old guilds a chance to cycle through and pop up again
4. Gives a new way to browse
5. Is a great touch!

**Describe alternatives you've considered**

* Sort by date joined
  * Also great, but a bit bleak

**Comment by kek7198** [comment]
@captainmeta4 thoughts?

In vue, I'm using sortable for more customization. Not something I'd take the time to implement in current ruqqus though.

**Comment by dginovker** [comment]
I forgot about Vue when I made this post. I'm happy to close given it won't be this way by the time I have kids and they hop on Ruqqus :)

**Comment by IThinkImOKAY** [comment]
vue is a lie
