### ISSUE TITLE
getting a 404 error on the "/" route

### ISSUE THREAD

**Issue by jaysridhar** [ruqqus/ruqqus#681]
On a fresh install, I am getting a 404 on the "/" route? Is this normal or am I missing some configuration?

## Expected Behavior
The site should come up when hitting the root URL (for example: https://example.com/)

## Current Behavior
Getting a 404 error page

## Possible Solution
Maybe I am missing some configuration? This is a fresh install of the latest master from github, with schema.sql used to initialize the database schema.

## Steps to Reproduce
1. Download or clone the master from github
2. Setup database as given in instructions
3. Initialize database with schema.sql in the repository
4. Start the flask application. Starts OK, but gives 404 on hitting the base URL

## Context (Environment)
No information of any kind in the logs, what might be wrong or missing.

**Comment by captainmeta4** [comment]
set SERVER_NAME environment variable; this might be `localhost` or `localhost:5000` or `localhost:someOtherPortNumber` depending on your setup.
