### ISSUE TITLE
How do we connect to docker ruqqus on Amazon EC2?

### ISSUE THREAD

**Issue by shillshocked** [ruqqus/ruqqus#685]
I can get this to work on localhost on my own computer. I want to deploy it to Amazon. What instructions should I follow to do so?

I've deployed it to EC2, run it, and can access it via ssh using lynx http://0.0.0.0:8000

Now how do I do this with a public address?

**Comment by captainmeta4** [comment]
Set `SERVER_NAME` environment variable
