### ISSUE TITLE
Add docs.google.com to the image whitelist

### ISSUE THREAD

**Issue by dginovker** [ruqqus/ruqqus#712]
**Is your feature request related to a problem? Please describe.**
* There is a huge potential for live updating data sets/graphs for at least one niche and growing guild on Ruqqus
* Imgur and other image hosting services don't work for this
* I'm trying to keep it a bit low-key

**Describe the solution you'd like**
* Google sheets, hosted on docs.google.com can actually create images; see this link for example: 

`![](https://docs.google.com/spreadsheets/d/e/2PACX-1vSFonoSx5dp02mTtj1hJGw1Z_ObCCcMrDqg39rJ-jfXFW_Xgi-Of5LYmD_hdhSyz94HlvsEyKUaLYIl/pubchart?oid=601662572&format=image)`
![](https://docs.google.com/spreadsheets/d/e/2PACX-1vSFonoSx5dp02mTtj1hJGw1Z_ObCCcMrDqg39rJ-jfXFW_Xgi-Of5LYmD_hdhSyz94HlvsEyKUaLYIl/pubchart?oid=601662572&format=image)

**Describe alternatives you've considered**
* Creating bots (a lot of effort, doesn't work for filthy casuals)

**Comment by captainmeta4** [comment]
![](https://docs.google.com/spreadsheets/d/e/2PACX-1vSFonoSx5dp02mTtj1hJGw1Z_ObCCcMrDqg39rJ-jfXFW_Xgi-Of5LYmD_hdhSyz94HlvsEyKUaLYIl/pubchart?oid=601662572&format=image)

**Comment by captainmeta4** [comment]
Done
