### ISSUE TITLE
The GM of guild can bypass being blocked after yanking from +general

### ISSUE THREAD

**Issue by ForeverZer0** [ruqqus/ruqqus#716]
If a post is made in +general, a user can yank it to a guild that they are GM of and bypass the personal user blocklist of those who have commented in that post, since they are now a GM and can see the comments of users who block them, even though these comments were not made within that guild, but while it was in +general.

## Expected Behavior
That this person I blocked should not be able to reply to my comments and give me notifications where I see their replies.

## Current Behavior
When I check notifications, I am able to see their reply, though it is blocked if I follow the link to the actual thread.

## Possible Solution
Not let a blocked user cause an alert no for any reason.

## Steps to Reproduce
1. Comment on a post in +general.
2. Have someone that user is blocking yank it into a guild that they are a GM of.
3. Have that blocked user reply to the comment, since they are GM and can see blocked users in "their" guild, although it was originally in +general.
4. Check notifications

## Context (Environment)
It happened to me.

## Detailed Description
See above.

## Possible Implementation
Users should not be able to comment if they are blocked, whether they yanked something from +general or not.

**Comment by IThinkImOKAY** [comment]
This is intentional.

You can see it in an incognito tab anyways.

**Comment by ForeverZer0** [comment]
@IThinkImOKAY It is intentional that a user you block can reply to you? That pretty much defeats the entire purpose of blocking. It isn't that I want to open a private tab and read their reply, the fact that can reply and it gives me notifications where I can read their reply is the issue.

**Comment by IThinkImOKAY** [comment]
@ForeverZer0 You are commenting in the guildmaster's guild. They should be able to reply to anything inside their guild.

**Comment by ForeverZer0** [comment]
@IThinkImOKAY No, I am commenting in +general. They then pull that post into a guild, and are free to make comments on existing comments that were in there. No comment was actually made within that guild, it was all in +general.

Of course as the GM they should be able to see posts/comments made in their own guild whether a user has blocked them or not, but another user having a conversation in +general should not be able to unexpectedly be getting replies from someone they blocked and was no part of the conversation they were having. 

Either way, just because someone is a GM does not mean they should be able to override a user's blocks to reply to a comment they made outside of that guild. If they want to exile the user, then go ahead, but I when a user blocks someone, there is an expectation of "they won't be replying to me nor I to them", especially when having a discussion outside of a guild they control.
