### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by Deauthorized** [ruqqus/ruqqus#737]
Sorry for using this as a forum, but I see no communication anywhere else. The only subdomain that works is .dev, which for some reason is entirely red and is titled "greeen". What's going on here?

**Comment by IThinkImOKAY** [comment]
I walked to Ruqqus LLC HQ, grabbed the computer running the site and typed `rm -rf remove *`.

You're welcome.

**Comment by captainmegafag** [comment]
LMAO GET REKT.
Finally gave up on that shit-hole aye Adam?
Did you get tired of being a Nazi?

**Comment by Deauthorized** [comment]
@captainmeta4 read my post assbutt
