### ISSUE TITLE
GM Invite Script broken

### ISSUE THREAD

**Issue by nochill-1** [ruqqus/ruqqus#741]
Issue tracker is **ONLY** used for reporting bugs.

## Expected Behavior

After clicking "Accept Invitation" I should be added as Guildmaster
## Current Behavior

Clicking "Accept Invitation" throws an alert
## Possible Solution

.../all_js.js Line 692 ```xhr.send(form)´´´ cant fetch a form because the file is missing. (404) (according to the debug console)
## Steps to Reproduce

1. 
![Selection_003](https://user-images.githubusercontent.com/80623482/117648608-b714d400-b18e-11eb-872e-0f369690d30a.png)

2.
3.
4.

**Comment by IThinkImOKAY** [comment]
I have noticed this as well. I notified kek on Discord, but I think cap will need to fix this.

**Comment by captainmeta4** [comment]
Fixed, this was part of an issue that affected all system notifs
