### ISSUE TITLE
Ruqqus.com/mine shows "Join" beside guild names - Despite them all being guilds you're a part of

### ISSUE THREAD

**Issue by dginovker** [ruqqus/ruqqus#755]
## Expected Behavior
https://ruqqus.com/mine should not have a "Join" button

## Current Behavior

![image](https://user-images.githubusercontent.com/32943174/119279965-e0a51500-bbfc-11eb-985c-33edb35ce01f.png)

## Possible Solution
1. Ignore until Vue
2. Change "Join" to "Visit"

**Comment by captainmeta4** [comment]
resolved
