### ISSUE TITLE
/create_guild page doesn't work with dark mode

### ISSUE THREAD

**Issue by dginovker** [ruqqus/ruqqus#756]
## Expected Behavior
https://ruqqus.com/create_guild shoud look dark when dark mode is enabled

## Current Behavior
![image](https://user-images.githubusercontent.com/32943174/119389240-578feb80-bc99-11eb-8ee2-fcc89e0fcd0e.png)

## Steps to Reproduce
1. Enable dark mode
2. Visit https://ruqqus.com/create_guild

## Possible Implementation
* Ignore until Vue

**Comment by kek7198** [comment]
Tested; it does work. Closing this issue.

**Comment by ruqqusBanido** [comment]
what browser'
